### ISSUE TITLE
Node.js App Server layer includes deprecated opsworks_nodejs::npm recipe (twice)

### ISSUE THREAD

**Issue by tristanls** [aws/opsworks-cookbooks#1]
It doesn't do anything, no need to be there, yes?

https://github.com/aws/opsworks-cookbooks/blob/master/opsworks_nodejs/recipes/npm.rb

**Comment by crekev** [comment]
Sure, you're right.  This will be removed soon. Thanks

**Comment by githuesch** [comment]
That file is still there, but OpsWorks stopped including it a long time ago.
