### ISSUE TITLE
Define the number of releases kept

### ISSUE THREAD

**Issue by linki** [aws/opsworks-cookbooks#103]
According to the docs on http://docs.opscode.com/resource_deploy.html#attributes chef allows to define the number of releases kept on the server with the `keep_releases` attribute which defaults to five.

Unfortunately, there seems to be no way to define a different value as the deploy resource definition doesn't care about it. see https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/deploy/definitions/opsworks_deploy.rb#L65

I'm currently working under heavy storage constraints and can't afford to keep more than one or two old releases. Adding support for this attribute would be awesome.

**Comment by donaldpiret** [comment]
+1 Those new M3 instances are great, but the small SSD's mean we have to be more careful with how we use storage space

**Comment by jbraeuer** [comment]
Thank you for reporting your issue and suggesting the enhancement. We will review your request.

**Comment by jbraeuer** [comment]
OpsWorks will introduce a new attribute, that allows to configure the releases kept. Once the change is deployed, it will be possible to configure the number of releases globally via

```
  { "opsworks": { "deploy_keep_releases": 5 } }
```

As an alternative, this can be configured on a per-application basis

```
{ "deploy": { "myapp": { "keep_releases": 5 } } }
```
