### ISSUE TITLE
Github Repository is behind

### ISSUE THREAD

**Issue by ryansch** [aws/opsworks-cookbooks#106]
I've been doing a lot of cookbook development on top of this repository the last few days.  I just discovered that the cookbooks that are actually installed on my instances are ahead of what is available here.  It would really help to have those changes published here at the same time they're pushed out to our instances.

**Comment by irony** [comment]
+1

**Comment by rcracel** [comment]
+1

**Comment by jbraeuer** [comment]
Thanks a lot for opening this issue. Sorry that the cookbook push was delayed - I just fixed it. The repository is now up to date.

Best,
Jens

**Comment by timhaines** [comment]
@jbraeuer Thanks for fixing it this time.  Can Opsworks make some kind of commitment to keeping them in sync going forward?  

Custom cookbooks we write often interact with the opsworks cookbooks.  Having what's in production actually differ to what is indicated (via github) to be in production can cause a lot of problems.

**Comment by jbraeuer** [comment]
Hi @timhaines. OpsWorks wants to make the Cookbook development more transparent. Starting today, there will be 2 branches per Chef version: _master-chef-XX_ and 
_release-chef-XX_.

_Release_ has the code currently deployed, while _master_ has the code for the upcoming version. If in doubt, you are probably using the Cookbook code in _release_. To be 100% sure, run `opsworks-agent-cli agent_report` on one of the instances. The reported agent version is the tag to look for.

Cookbook changes will be pushed to _master_ branch first. When a release is started, a new tag is created. When a release is done and deployed, the _master_ branch will be merged into the _release_ branch.
