### ISSUE TITLE
Unicorn worker_processes default to node[:rails][:max_pool_size] doesn't make sense.

### ISSUE THREAD

**Issue by azuby** [aws/opsworks-cookbooks#119]
https://github.com/aws/opsworks-cookbooks/blob/945499863560cac1e2c4454adc4a5601b1094e63/unicorn/attributes/default.rb#L19

The line above set's the number of unicorn worker's per server instance equal to the max pool size of the database. Since unicorn uses separate processes for concurrency rather than multithreading, it seems this could cause performance problems as you increase the number of instances and pool size.

Relevant StackOverflow answer: http://stackoverflow.com/a/22404491

**Comment by azuby** [comment]
I think I may have mistook the max_pool_size for the max database pool size which appears to be reading the pool attribute from the custom database json here: https://github.com/aws/opsworks-cookbooks/blob/945499863560cac1e2c4454adc4a5601b1094e63/rails/templates/default/database.yml.erb#L11

I don't see anywhere in the documentation<sup>1</sup> mentioning the "pool" attribute and a quick search reveals that the max_pool_size attribute is only being used in the recipes to determine the number of unicorn workers, not configure the pool size (as it says in the documentation<sup>2</sup>)

<sup>1</sup> http://docs.aws.amazon.com/opsworks/latest/userguide/attributes-json-deploy.html#attributes-json-deploy-app-db
<sup>2</sup> http://docs.aws.amazon.com/opsworks/latest/userguide/attributes-json-other.html

**Comment by ryansch** [comment]
Agreed.  The default setup for unicorn doesn't make much sense.  I've overridden the logic in my stack to have the most unicorns I can run per instance (based on our app and benchmarking).  Haproxy also knows this number and only farms out that many simultaneous connections to each app box.  The result: very fast.

**Comment by ryansch** [comment]
Here's the unicorn config erb template I use for 0 downtime deploys: https://gist.github.com/ryansch/d551525afcf0cc26b463

With that configuration, there's never any need to run a 'clean restart' from the unicorn service script.

**Comment by jweiss** [comment]
closing as this is a very old issue

**Comment by jweiss** [comment]
closing as this is a very old issue
