### ISSUE TITLE
Suggested changes for NodeJs

### ISSUE THREAD

**Issue by irony** [aws/opsworks-cookbooks#120]
There are quite a few things in the initial setup that are inconsistent with how NodeJs apps are usually set up. I have created a fork of the official cookbook to fix these things and also added MongoDb and Redis. 

I will try to split these changes into separate pull requests so you can accept them individually but for anyone that are interested in the meantime, please give your thoughts to the implementation here:
[irony/opsworks-cookbooks](https://github.com/irony/opsworks-cookbooks)

**Comment by awsrequena** [comment]
thanks
