### ISSUE TITLE
Incorrect Gemfile changes detection

### ISSUE THREAD

**Issue by dnagir** [aws/opsworks-cookbooks#121]
The method `different_gemfile?` [compares the current and previous](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/unicorn/templates/default/unicorn.service.erb#L28) `Gemfile` to check if it was changed.

The problem is that the `Gemfile` doesn't have to be changed for the gems to be updated. The `Gemfile.lock` holds full data about the gems to be loaded. `Gemfile` is just a manifest for `bundler`.

As a result of this an update to a gem (vai `bundle update my_gem`) will not be reflected on the deployment and the old gem (and all its dependencies) will be used instead.

**Comment by swrobel** [comment]
:+1:

**Comment by evdevdev** [comment]
Is this really necessary? I believe that unicorn restarts should not accidentally cache the gemfile.

Is there any proof or evidence that unicorn can get stuck? The master process is getting recycled so, this shouldn't be an issue.

 I have  different pull request to pull this out entirely: https://github.com/aws/opsworks-cookbooks/pull/180

**Comment by evdevdev** [comment]
I have more information on this. From the unicorn documentation: 

> HUP - reloads config file and gracefully restart all workers. If the “preload_app” directive is false (the default), then workers will also pick up any application code changes when restarted. If “preload_app” is true, then application code changes will have no effect; USR2 + QUIT (see below) must be used to load newer code in this case. When reloading the application, Gem.refresh will be called so updated code for your application can pick up newly installed RubyGems. It is not recommended that you uninstall libraries your application depends on while Unicorn is running, as respawned workers may enter a spawn loop when they fail to load an uninstalled dependency.

So it looks like we need a USR2. That is taken care of here: https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/unicorn/templates/default/unicorn.service.erb#L61

This should be followed by a QUIT. This is taken care of here: https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/unicorn/templates/default/unicorn.conf.erb#L41

**Comment by awsrequena** [comment]
@dnagir so we basically we should checksum Gemfile.lock instead of Gemfile. After rereading the bundler's man page, this really makes sense.

> If a Gemfile.lock does exist, and you have not updated your Gemfile(5), bundler will fetch all remote sources, but use the dependencies specified in the Gemfile.lock instead of resolving dependencies.
>  If a Gemfile.lock does exist, and you have updated your Gemfile(5), bundler will use the dependencies in the Gemfile.lock for all gems that you did not update, but will re-resolve the dependencies of gems that you did update

\- from http://bundler.io/man/bundle-install.1.html
