### ISSUE TITLE
lvm cookbook inclusion causes setup failure on 11.10

### ISSUE THREAD

**Issue by heffergm** [aws/opsworks-cookbooks#122]
It appears that there's some sort of conflict on the chef 11.10 release branch with the opscode lvm cookbook (I've tested everything from 1.0.0 to 1.0.8 with the same result).

When a cookbook that references lvm via metadata is includes in the run list, it leads to various failures, usually manifesting as failure to call split on nilClass, but in essence these are red herrings (or so it seems to me at present). Oddly, a second run resolves the issue.

Anyone else having issues with lvm on 11.10?

**Comment by ujuettner** [comment]
Thanks for reporting this issue.
We are currently working on a fix.

**Comment by ujuettner** [comment]
The AWS OpsWorks Instance Agent version 306, which includes the fix, is now rolled out. The release-chef-11.10 branch is updated accordingly.
