### ISSUE TITLE
Circular dependency: dependencies, opsworks_nodejs, deploy, dependencies

### ISSUE THREAD

**Issue by grampajoe** [aws/opsworks-cookbooks#128]
There's a circular dependency when trying to install anything that depends on `dependencies` with Berkshelf 3.0.0.beta8 and above: `dependencies` -> `opsworks_nodejs` -> `deploy` -> `dependencies`.

This results in Berkshelf hitting the maximum stack depth and crashing when trying to resolve transitive dependencies.

Should this be considered a bug in Berkshelf/its dependency resolver, or is it something that can be addressed by rearranging the OpsWorks cookbook dependencies?

**Comment by githuesch** [comment]
I didn't check yet if this could be fixed by changing the dependencies cookbook, but I think it should not be needed to change anything. You don't need to include any of our cookbooks as dependencies in your Berksfile. Our built-in cookbooks will be made available to the Chef run, no matter which cookbooks you install through Berkshelf.

**Comment by grampajoe** [comment]
I'm using Berkshelf to install these cookbooks for testing with Chefspec. The development process is too long if I have to test on Opsworks itself.

**Comment by githuesch** [comment]
Got it, good point. We'll look into this.

**Comment by stepking** [comment]
This does cause a problem however if you want to override opsworks cookbooks. If you want to do that, you have to pretty much add all of the opsworks cookbooks to your berkshelf file. If you include just a few, it will fail as berkshelf isn't able to install the dependencies referenced in the opsworks metadata (as they reference cookbooks not available from the community repo). This is another type of situation where the circular dependency issue causes problems.

**Comment by githuesch** [comment]
@grampajoe The fact that circular dependencies cause Berkshelf to crash is a problem in Berkshelf itself, see https://github.com/berkshelf/solve/issues/41. I haven't checked all metadata references among OpsWorks cookbooks, but I guess at least some of them can be removed through refactoring.

@stepking None of the OpsWorks cookbooks are available from the community repo. As soon as you use any single one of them that has at least one dependency, and you don't also satisfy that dependency, you run into a problem. But I don't understand how your description is related to circular dependencies. Can you elaborate further?

**Comment by stepking** [comment]
@githuesch - sure, what I mean is that if you use berkshelf and add all of the necessary opsworks cookbooks (either by referencing them on github or by using "path" to point to the default cookbooks on the instance) to the Berksfile, and do "berks vendor", it will fail quietly (the failure isn't logged in opsworks logs) because berkshelf encounters a circular loop. So even though berkshelf actually can find all the dependencies, the loop causes it to fail.

**Comment by githuesch** [comment]
@stepking Got it. Berkshelf's output currently doesn't show up in the logs at all, no matter if it succeeds or fails. I fixed that today and it will be released with an upcoming agent rollout, so you at least see what's happening. Getting rid of the dependencies will be a bit more involved, though.

**Comment by ryansch** [comment]
This particular bug is fixed in berkshelf 3.1.2 and up.

**Comment by ryansch** [comment]
For clarity, Opsworks has made berkshelf 3.1.3 available via a package.  See: https://forums.aws.amazon.com/message.jspa?messageID=562087#562087

**Comment by longk15t** [comment]
Hi,
I got this error, I'm using berkshelf 6.3.0, any idea how to fix? This is my output command
![image](https://user-images.githubusercontent.com/6722910/29557581-c5a5888e-8753-11e7-8f91-9b7e98920882.png)

This is my Berksfile

> source "https://supermarket.chef.io"
> 
> metadata
> 
> # The following all come from the default AWS OpsWorks cookbook repo.  We will
> # use this to try to mimic the OpsWorks init process as accurately as possible.
> 
> def opsworks_cookbook(name, branch = 'release-chef-11.10', git = "https://github.com/aws/opsworks-cookbooks.git")
>   cookbook name, git: git, branch: branch, rel: name
> end
> 
> opsworks_cookbook "opsworks_initial_setup"
> 
> opsworks_cookbook "mysql"
> 
> opsworks_cookbook "opsworks_shutdown"
> 
> opsworks_cookbook "opsworks_commons"
> 
> opsworks_cookbook "dependencies"
> 
> opsworks_cookbook "gem_support"
> 
> opsworks_cookbook "opsworks_nodejs"
> 
> opsworks_cookbook "deploy"
> 
> opsworks_cookbook "scm_helper"
> 
> opsworks_cookbook "apache2"
> 
> opsworks_cookbook "mod_php5_apache2"
> 
> opsworks_cookbook "nginx"
> 
> opsworks_cookbook "ssh_users"
> 
> opsworks_cookbook "ssh_host_keys"
> 
> opsworks_cookbook "opsworks_agent_monit"
> 
> opsworks_cookbook "passenger_apache2"
> 
> opsworks_cookbook "unicorn"
> 
> opsworks_cookbook "opsworks_java"
> 
> opsworks_cookbook "php"
> 
> opsworks_cookbook "opsworks_aws_flow_ruby"
> 
> opsworks_cookbook "opsworks_ganglia"
> 
> opsworks_cookbook "agent_version"
> 
> opsworks_cookbook "rails"
> 
> opsworks_cookbook "packages"
> 
> opsworks_cookbook "opsworks_postgresql"
> 
> cookbook "build-essential", "= 3.2.0"

**Comment by emmahsax** [comment]
@ryansch Yes, I'm seeing the same error using berkshelf ~> 4.1.0 as well.
