### ISSUE TITLE
unable to override symlink_before_migrate

### ISSUE THREAD

**Issue by willzofsteel** [aws/opsworks-cookbooks#129]
Hello,
Currently we are trying to override the default behavior in opsworks for a Rails layer.  We have a database.yml that we check in, and supply the credentials in through another mechanism.  Opsworks default deploy is overriding this via a symlink its doing to a database.yml.  We purposely do not set the database host in the custom json, which doesn't create the shared/config/database.yml which results in a symlink to nothing.

we tried setting the custom json with

```
"symlink_before_migrate": {}
```

```
"symlink_before_migrate": nil
```

no cigar and then we tried overriding this behavior with the following directly in a attributes/default.rb in one of our recipes and nothing

```
normal[:deploy][:phoenix][:symlink_before_migrate] = {}
```

connecting to the failed box, and outputting json we can see:

```
"symlink_before_migrate": {
        "config/database.yml": "config/database.yml",
        "config/memcached.yml": "config/memcached.yml"
      },
```

any clue or ideas on how we get that to not contain the database.yml line?
Thank you

**Comment by kstevens** [comment]
Ended up adding a custom recipe to explicitly disable symlinks:

``` ruby
node[:deploy].each do |application, deploy|
    node.normal[:deploy][application][:symlink_before_migrate].clear
end
```

**Comment by githuesch** [comment]
I think your custom recipe will have to stay a permanent solution for the time being. Merging custom JSON into OpsWorks' own configuration values effectively boils down to merging hashes in memory. So adding or overwriting keys is possible, removing keys isn't.

Once we move those defaults from our backend into our cookbooks, providing an attribute file will allow you to override our defaults. I will create a backlog item for making that change.

**Comment by ph4t** [comment]
Is this recipe still working? 

In my case, the recipe gets executed and I've verified that node.normal[:deploy][application][:symlink_before_migrate] is empty. However, later in the deployment, symlink_before_migrate still gets executed resulting in database.yml overwrite...

**Comment by jcarlson** [comment]
What's the status on moving defaults from the "backend" to a cookbook? I've lost too many hours trying to stop the stack from symlinking database.yml and add a new file to be symlinked and am not having much luck.

**Comment by fmasuhr** [comment]
I tried the solution with custom recipe but did not got it working properly. How do i get this working?
Or is there maybe news on a better way to get OpsWorks to not override `database.yml` with empty symlink?

**Comment by russau** [comment]
@kstevens which lifecycle event did you attach your custom recipe to?

**Comment by real-mj-song** [comment]
If anyone still encounters this issue, this can be fixed by using `default` precedence in `attributes/default.rb`
```
default[:deploy][:phoenix][:symlink_before_migrate] = {}
```

Chef replaces a hash attribute when it's changed at the same level (See https://github.com/chef/chef/issues/1911#issuecomment-54528383). Otherwise, they get merged. So to override a `default` attribute, you need to override it with another `default` attribute.
