### ISSUE TITLE
Berkshelf cookbooks directory not deleted before new checkout

### ISSUE THREAD

**Issue by grampajoe** [aws/opsworks-cookbooks#132]
Starting with v307, Chef runs with "Manage Berkshelf" set to "yes" fail when checking out custom cookbooks. The initial Setup run when an instance boots succeeds, but the Configure run and any command after that fails.

This is caused by not deleting the `/opt/aws/opsworks/current/berkshelf-cookbooks` directory before calling `berks vendor` with Berkshelf 3.

**Comment by grampajoe** [comment]
More details: this only applies to Berkshelf 3, since the `berks vendor` command requires that the directory doesn't already exist.

**Comment by githuesch** [comment]
Can you check if you still run into this with version 307? We just finished rolling this out yesterday and it comes with improved Berkshelf integration. Also, I just tried a few things myself and didn't see errors in the subsequent runs.

**Comment by grampajoe** [comment]
Sorry, that's what I meant. It only happens with v307 and the new opsworks_berkshelf::purge recipe with Berkshelf v3.0.0.beta7.

**Comment by githuesch** [comment]
Got it, working on a fix.

**Comment by grampajoe** [comment]
Is there a way I can work around this for now? I'm not _completely_ stuck, but I'm mostly stuck.

**Comment by jsierles** [comment]
Same issue here - haven't been able to work around this since the berkshelf recipes always run before others and can't be overridden.

**Comment by jsierles** [comment]
Also, the not_if is not the issue - this code was written to purge the cookbooks when you turn off 'Manage with berkshelf?'. There needs to be NEW code that deletes the berkshelf cookbook directory before vendoring. An alternative approach could be to not use the vendor command and use the cookbooks  directory wherever Berkshelf caches them.

**Comment by grampajoe** [comment]
@jsierles Good point! I'll update the issue.

**Comment by githuesch** [comment]
@grampajoe @jsierles You're right, there needs to be new code. I just wrote and tested it, it will be included in the next agent version. Using Berkshelf's cache is not a good idea, though. This is also mentioned in Berkshelf's documentation. In theory every cookbook out there uses metadata to set its name. In practice there are still plenty of cookbooks that don't, and Chef itself uses the name of the cookbook directory as the cookbook name rather than what's defined in metadata. The directory names in the cache directory are composed of the actual name and the version, hence the official recommendation against using it as a cookbook source in Chef runs directly.

**Comment by githuesch** [comment]
There's actually one thing you can do to force deletion of the Berkshelf cookbooks. Turn 'Manage Berkshelf' off and run update_custom_cookbooks so the prune recipe kicks in. Then turn it on again to have fresh cookbooks installed with Berkshelf.

**Comment by jsierles** [comment]
@githuesch Thanks for the update. Good to know about the cache. Just to confirm, is there a way to inject code or override the cookbooks in this run?

**Comment by githuesch** [comment]
@jsierles No, you got that one right as well. At the moment you can't modify that stage. We're eagerly working on fixing the existing issues with Berkshelf and also making Berkshelf usage tweakable, e.g. allowing to pass `--debug` to the invocation.

**Comment by grampajoe** [comment]
I wasn't able to get the `berkshelf-cookbooks` directory deleted by turning off Manage Berkshelf and running `update_custom_cookbooks`.

What worked for me was executing these recipes:

```
opsworks_custom_cookbooks::berkshelf,opsworks_berkshelf::purge
```

with the JSON

```
{"opsworks_custom_cookbooks": {"manage_berkshelf": false}}
```

Including `opsworks_custom_cookbooks::berkshelf` was done to provide access to the `uninstall_other_gem_versions` function from `opsworks_custom_cookbooks`.

It's a totally hacky workaround, but it meant I could do that and then run a Deploy or Configure without problems, and then just do a Retry on the workaround command without having to change stack settings.

@githuesch Thanks for all the work you and the OpsWorks team are doing! Even with the issues, the alternative is a lot more work. I'm looking forward to the new agent release.

**Comment by grampajoe** [comment]
I should also mention that starting a new instance will still fail on the Configure step, so the above workaround needs to be run on that instance and then Configure needs to be re-run to complete the setup process.

**Comment by githuesch** [comment]
@grampajoe Thanks for the details, and I'm glad to hear what you're saying. If `berkshelf-cookbooks` isn't removed when `manage_berkshelf` is set to `false`, this is a bug. We'll investigate this one as well.

**Comment by githuesch** [comment]
@grampajoe Removal of berkshelf cookbooks when `manage_berkshelf` is set to `false` is fixed as well, will also be part of the next agent release.

**Comment by githuesch** [comment]
@jsierles @grampajoe This is in production now.
