### ISSUE TITLE
X-Request-Start "t=${msec}" Breaks on Ubuntu 12.04

### ISSUE THREAD

**Issue by glance-** [aws/opsworks-cookbooks#135]
7fa3d1fe6e2551041ca06e42880b2ff89c956404 broke deployents on 12.04.

msec doesn't exist as vairable on 12.04, and this code should be conditionalized on deployments to a newer nginx.

**Comment by githuesch** [comment]
We're on it.

**Comment by githuesch** [comment]
https://github.com/aws/opsworks-cookbooks/commit/352521c5f3b59c70c63dca6c726883dd336b7b48 reverts the change you mentioned and we're pushing it out at the moment.

**Comment by githuesch** [comment]
The fix is pushed out.

**Comment by glance-** [comment]
Gee, that was fast. Thanks mate!
