### ISSUE TITLE
Translate special characters to entity elements for database passwords

### ISSUE THREAD

**Issue by joemccall86** [aws/opsworks-cookbooks#137]
Our RDB database password has an ampersand. When opsworks creates my context XML file it passes in the '&' character instead of &amp;amp;, which causes a parsing error.

Here's a table of them for XML I found on the internet:

| symbol | escaped |
| --- | --- |
| & | &amp;amp; |
| < | &amp;lt; |
| > | &amp;gt; |
| " | &amp;quot; |
| ' | &amp;apos; |

**Comment by githuesch** [comment]
Thanks for bringing this up, we'll have a look.
