### ISSUE TITLE
Runit release 11.10 is missing.

### ISSUE THREAD

**Issue by mhalligan** [aws/opsworks-cookbooks#139]
Hi, could somebody please push the 11.10 release branch of the runit cookbook? The branch itself exists but nothing is there.

**Comment by heffergm** [comment]
Could you clarify? Before the 11.10 migration, I (and others) wanted nothing more than to see the included runit cookbook removed from the opsworks cookbook repo. It's gone in 11.10 and I'm certainly glad that it is... I can now use whatever version I want to that suits my needs. If someone adds a runit cookbook back into the 11.10 release branch at this point it's going to completely hose a great deal of my infrastructure.

I may be missing what you're after, so if I'm off, just ignore me ;)

**Comment by githuesch** [comment]
Exactly. We removed the runit cookbook on customer demand, see https://github.com/aws/opsworks-cookbooks/commit/3ceec03cf2e25612bb2a064aa3d01396baacfdb4. Feel free to use Berkshelf to install it from the community site.
