### ISSUE TITLE
`rake validate_attribute_dependencies` doesn't work

### ISSUE THREAD

**Issue by dznz** [aws/opsworks-cookbooks#14]
Getting the error: 

```
undefined method 'each' for "<line_string>":String
```

where `<line_string>` appears to be the first line from an attribute file.

**Comment by githuesch** [comment]
Sorry getting back so late. Is this still an issue now? If so, which versions of Ruby and Rake are you using?

**Comment by dznz** [comment]
I think it's been too long to bother trying to reproduce again, given no-one else has complained. I'm going to close this issue, and someone can open a fresh one if they are still experiencing it. Cheers for getting back to me, though!

**Comment by githuesch** [comment]
You're welcome, and sorry again for getting back so late.
