### ISSUE TITLE
Compile Error in Unicorn Recipe

### ISSUE THREAD

**Issue by dwinders** [aws/opsworks-cookbooks#140]
Currently using Chef 11.10 and am trying to start a Rails Instance via Opsworks, but it fails once it gets to the unicorn recipe on during setup.
# 
# Recipe Compile Error in /var/lib/aws/opsworks/cache/cookbooks/unicorn/attributes/default.rb
## Chef::Exceptions::CookbookNotFound

Cookbook rails not found. If you're loading rails from another cookbook, make sure you configure the dependency in your metadata
## Cookbook Trace:

/var/lib/aws/opsworks/cache/cookbooks/unicorn/attributes/default.rb:17:in `from_file'
## Relevant File Content:

/var/lib/aws/opsworks/cache/cookbooks/unicorn/attributes/default.rb:

10:  #
11:  # Do NOT create an 'unicorn/attributes/default.rb' in your cookbooks. Doing so
12:  # would completely override this file and might cause upgrade issues.
13:  #
14:  # See also: http://docs.aws.amazon.com/opsworks/latest/userguide/customizing.html
15:  ###
16:  
17>> include_attribute 'rails::rails'
18:  
19:  default[:unicorn][:worker_processes] = node[:rails][:max_pool_size] ? node[:rails][:max_pool_size] : 4
20:  default[:unicorn][:backlog] = 1024
21:  default[:unicorn][:timeout] = 60
22:  default[:unicorn][:preload_app] = true
23:  default[:unicorn][:version] = '4.7.0'
24:  default[:unicorn][:tcp_nodelay] = true
25:  default[:unicorn][:tcp_nopush] = false
26:  default[:unicorn][:tries] = 5

[2014-05-23T21:42:26+00:00] ERROR: Running exception handlers
[2014-05-23T21:42:26+00:00] ERROR: Exception handlers complete
[2014-05-23T21:42:26+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-05-23T21:42:26+00:00] ERROR: Cookbook rails not found. If you're loading rails from another cookbook, make sure you configure the dependency in your metadata
[2014-05-23T21:42:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by githuesch** [comment]
That's because unicorn/attributes/default.rb includes an attribute from the rails cookbook without having this dependency specified in metadata.rb. Thanks for pointing this out, we will fix this with an upcoming release.

**Comment by dwinders** [comment]
Thanks for the quick response ... when would the next release be? This is kind of a blocking issue since no Rails Apps can be created using chef 11.10.

**Comment by githuesch** [comment]
We can't tell you when the next release will be, but there's probably a workaround. When using Chef 11.10, OpsWorks merges cookbooks from different sources in the filesystem. Your runs fail because unicorn/metadata.rb doesn't contain the line "depends 'rails'". If you create unicorn/metadata.rb in your custom cookbooks and add that line there, that file will be used and the rails cookbook will be loaded.

**Comment by tlobinger** [comment]
This should be fixed.
