### ISSUE TITLE
How to disable PassengerFriendlyError pages

### ISSUE THREAD

**Issue by willzofsteel** [aws/opsworks-cookbooks#142]
Hi,
We were having an issue with an opswork rails stack.  Basically on certain errors we get a passenger error which displays all the information of things we don't want displayed (i.e environment variables, etc) The docs for phusion say its possible to set the value in the config file.  Manually doing this does in fact work. Now we want to apply this to our opsworks recipes, by providing an override but haven't had any luck doing so. 
we were hoping we would only need to do something like

```
default[:passenger][:friendly_error_pages] = 'off'
```

whats the correct way in opsworks to disable the PassengerFriendlyError pages?

**Comment by willzofsteel** [comment]
Just overwrote passenger.conf through a custom recipe.

**Comment by githuesch** [comment]
As you can see in https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/passenger_apache2/attributes/passenger.rb#L66, we already added the line you mentioned to our attributes. At the moment it's only available in the cookbooks for Chef 11.10. I'll add it to the ones for Chef 11.4. Thanks for bringing this up.
