### ISSUE TITLE
How can I modify context.xml of Tomcat ?

### ISSUE THREAD

**Issue by KnightYusuf** [aws/opsworks-cookbooks#148]
I want to add this code in /usr/share/tomcat7/conf/context.xml :

< Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
              sticky="true"
              memcachedNodes="n1:<%= node['redis']['host']%>:<%= node['redis']['port']%>"
              requestUriIgnorePattern=".*.(ico|png|gif|jpg|css|js)$"
     />

how can i do that?
thanks.

**Comment by KnightYusuf** [comment]
Finally I've found the solution I've created a template of the context.xml file: opsworks-cookbooks/opsworks_java/templates/default/context.xml.erb
<?xml version='1.0' encoding='utf-8'?>
<Context>
    
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
          sticky="true"
          memcachedNodes="n1:<%= node['redis']['host']%>:<%= node['redis']['port']%>"
          requestUriIgnorePattern=".*.(ico|png|gif|jpg|css|js)$"   />
</Context>

then i call it in opsworks-cookbooks/opsworks_java/recipes/tomcat_container_config.rb by adding the following lines:

template 'tomcat context configuration' do
  path ::File.join(node['opsworks_java']['tomcat']['catalina_base_dir'], 'context.xml')
  source 'context.xml.erb'
  owner 'root'
  group 'root'
  mode 0644
  backup false
  notifies :restart, 'service[tomcat]'
end

And it works fine!

**Comment by jweiss** [comment]
You can override built-in templates like this: http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-template-override.html
