### ISSUE TITLE
Fix rails deploy permissions

### ISSUE THREAD

**Issue by awithersdd** [aws/opsworks-cookbooks#15]
Add group to deploy resource, without this deploy will chown deploy.root everything.

diff --git a/deploy/definitions/opsworks_deploy.rb b/deploy/definitions/opsworks
index d7d0c05..39b07c2 100644
--- a/deploy/definitions/opsworks_deploy.rb
+++ b/deploy/definitions/opsworks_deploy.rb
@@ -60,6 +60,7 @@ define :opsworks_deploy do
     deploy deploy[:deploy_to] do
       repository deploy[:scm][:repository]
       user deploy[:user]
-      group deploy[:group]
     revision deploy[:scm][:revision]
     migrate deploy[:migrate]
     migration_command deploy[:migrate_command]

**Comment by ryansch** [comment]
This issue has been resolved and should be closed.

**Comment by githuesch** [comment]
Closing as per @ryansch's comment.
