### ISSUE TITLE
SSL Certificates for Node.js

### ISSUE THREAD

**Issue by martinheidegger** [aws/opsworks-cookbooks#151]
Right now it seems like the SSL certificates are passed to Apache but starting to listen to a https port with Node seems not to be working properly.

**Comment by githuesch** [comment]
The cookbook for Node.js currently doesn't handle SSL at all. We're on it.

**Comment by githuesch** [comment]
SSL support for Node.js applications was added in https://github.com/aws/opsworks-cookbooks/commit/10f53b86b4350453a993b84c67aa20470e811059, I just never got around to reply here. Sorry about that.

**Comment by martinheidegger** [comment]
Thank you for not the notification. Will try out if I can make it work.

**Comment by githuesch** [comment]
Does this work for you?
