### ISSUE TITLE
Annoying "system" symlink with PHP deployments

### ISSUE THREAD

**Issue by lracicot** [aws/opsworks-cookbooks#153]
Opswork creates a basic architecture in the "shared" directory with the following dirs: "log","config","system","pids","scripts","sockets". After that, It creates a symlink: 'public/system', "tmp/pids", and "log".

In the doc it says "A typical Ruby on Rails application will have config, log, pids, and system directories within the shared directory". Why would this also apply to PHP? I think It really depends on the framework, and a standard deployment script should not assume the use of a particular framework.

This cause me a lots of troubles when I have a CodeIgniter app and it's "system" directory is deleted by chef on the deployment. Also, when I have a Symfony app, opswork create a completely useless "public/system" symlink to a "system" directory that Symfony never uses.

**Comment by lracicot** [comment]
I also posted on stackoverflow for a workaround... nobody seems to have one.
http://stackoverflow.com/questions/24315413/prevent-opsworks-from-overwriting-the-codeigniters-system-directory-with-a-sy

**Comment by nappa32** [comment]
There is a work around to this behaviour. I have posted that in the above link. There are hooks you can utilise to fix this. 

#### deploy/before_migrate.rb (in your app repo )

```
deploy_to = deploy_resource.deploy_to

dirs_to_protect = [ "public" ]
dirs_to_protect.each {|dir| 
    bash "save #{dir}" do
      code <<-EOL
        cp -a #{release_path}/#{dir}/* #{deploy_to}/shared/#{dir} 
      EOL
    end
}
```

**Comment by lracicot** [comment]
This could work for a moment. It also comfirm that there is a conceptual problem with that cookbook.

**Comment by awsrequena** [comment]
Hello,

as pointed out by @nappa32 (thanks a lot!), you can do something about this with the current tool set.

We're not going to merge your pull request as it will change the current deployment behaviour and thus possibly break current customers.

Nevertheless thank you very much for your feedback.

**Comment by jmcollin78** [comment]
I run in the same case cause Mean Stack utilize a /public/system repo by default. This is very strange and unlikely to change the applications structure at deployment. I hope you will do something in the future.
