### ISSUE TITLE
Ability to pin to a particular minor ruby version (2.1.1 vs 2.1.2)

### ISSUE THREAD

**Issue by bwilkins** [aws/opsworks-cookbooks#156]
I'm looking to be able to pin the particular ruby version that gets installed, For instance I may want to keep Ruby 2.1.1 installed instead of automatically rolling over to Ruby 2.1.2. An instance where this is important is when the ruby version is specified in the Gemfile of the project being deployed - our app would be deployed, specifying ruby 2.1.1, and suddenly it's exploding because we're attempting to run it with ruby 2.1.2.

I've had a look at the ruby recipes, and my main point of concern would be the availability of deb/rpm packages for the specified version - this is not knowledge I currently have. Would it be appropriate for me to a) develop my own solution and submit a pull request, b) fork away and do my own thing or c) wait for somebody else to tackle the same problem?

**Comment by githuesch** [comment]
You should be able to do this by adding custom JSON to your stack as follows.

``` JSON
{
  "ruby": {
    "patch_version": "1"
  }
}
```

**Comment by heffergm** [comment]
I had been doing this, but it recently broke. I was told the correct method was now:

``` json
{
  "opsworks": {
    "ruby_version": "2.0.0"
  },
  "ruby": {
    "patch_version": "p353"
  }
}
```

**Comment by githuesch** [comment]
@heffergm Good point, you're right. node[:opsworks][:ruby_version] is used in other cookbooks. I only tested with a minimal example, so setting up Ruby alone works with my snippet, but yours is more complete.

**Comment by bwilkins** [comment]
Hey guys,

It seems a bit odd to me that the opsworks ruby cookbook changes the attributes structure between ruby 2.0.0 and 2.1. Ruby 2.0.0 and earlier use "major_version", "full_version", "patch_version" and "pkgrelease", whereas Ruby 2.1 uses "major_version", "minor_version", "patch_version" and "pkgrelease".

Not to mention conflating language versions and package version systems, and mixing their terms...

Mini-rant over, it looks like I can get what I want with the recommendation of @githuesch. @heffergm's point is also valid, However I am using a Rails App layer, which I believe populates the node[:opsworks][:ruby_version] field for me.

Thanks guys!

**Comment by jweiss** [comment]
@bwilkins One reason for the change was the Ruby itself changed their versioning. Until Ruby 2.1, Ruby didn't use semantic versioning, now they do. So where you had 1.9.3-p123 and 1.9.3-p321 before they now use 2.1.1 and 2.1.2. 

Ideally our JSON would have stayed the same though, I agree and am sorry for any issues you had out of this.

**Comment by jordanfbrown** [comment]
This is what I had to add to my stack settings to lock down to Ruby 2.2.3:

```
"opsworks": { 
  "ruby_version": "2.2"
},
"ruby": {
  "patch_version": "3"
}
```
