### ISSUE TITLE
copytruncate breaks tail-reading rsyslog imfile

### ISSUE THREAD

**Issue by glance-** [aws/opsworks-cookbooks#159]
We use rsyslog and imfile to tailread the application logs to ship them away from the local machines to do later processing and analytics.

The copytruncate directive in deploy/templates/default/logrotate.erb confuses imfile because the file shrinks underneath it. It would be better if each program logging there would get a SIGHUP/SIGUSR1 after the rotation to reopen there logfiles instead of snarfing them underneath them.

Because of the shared nature of having that template deployed from the definition opsworks_deploy its kinda hard to override it in a app-specific way too.

As far as i can understand its only unicorn that logs to that dir? why is it in the common deploy cookbook then?

**Comment by awsrequena** [comment]
I see your point.  We should give the customer the possibility to set the logrotate configuration specifically for the deployed app/stack configuration.

**Comment by samdengler** [comment]
I think we've just encountered the same problem.  Is https://github.com/joeyAghion/opsworks_papertrail/issues/1 our best option or is there a more supported solution from OpsWorks at this point?

**Comment by selivan** [comment]
Just FYI guys: rsyslog starting from 8.16 has imfile option `reopenOnTruncate` (default off) that fixes the problem
