### ISSUE TITLE
Disappearing nginx pid file

### ISSUE THREAD

**Issue by heffergm** [aws/opsworks-cookbooks#164]
All my app servers that run nginx are suffering from a disappearing pid file. The result of which is twofold: 
- when logrotate runs, the USR1 never makes it to the process, and nginx stops logging
- normal attempts to stop the process using 'service' don't work

I haven't dug into why the pid file is going missing yet, but if you have any ideas in the meantime...

**Comment by ujuettner** [comment]
Thanks for reporting this issue. The default location of the PID file used by the nginx init script changed from /var/run/nginx.pid to /run/nginx.pid with Ubuntu 14.04 LTS.
Gonna fix this.

**Comment by heffergm** [comment]
Not sure that I see how that would impact things, since /var/run is a symlink to /run.

**Comment by ujuettner** [comment]
Haven't dug through nginx's source code, but if you use strace to chase down who's deleting /run/nginx.pid, you see that it's the nginx binary itself. It first writes the PID to /run/nginx.pid, and shortly after removing the file (maybe it thinks it has to clean up the old pid file, after having written the new one, as their file names differ - strace unfortunately seem to show dereferenced file names).
However, using /run/nginx.pid in nginx/templates/default/nginx.conf.erb works fine - /run/nginx.pid exists after the Chef run.

**Comment by ujuettner** [comment]
We are currently rolling out an agent version that contains a fix - it can be previewed as https://github.com/aws/opsworks-cookbooks/commit/a4e508801f01831e7ee0e95cd03769b569d50e9f .
