### ISSUE TITLE
Add docker deployment options

### ISSUE THREAD

**Issue by thomascramer** [aws/opsworks-cookbooks#167]
There is already some examples of people using docker with opsworks [1][2].  It would be nice to get these integrated so we can deploy/configure with docker.  

[1] http://www.slideshare.net/jweiss/docker-on-aws-opsworks
[2] http://www.shopigniter.com/blog/2014/04/01/deploying-docker-with-opsworks/

**Comment by irony** [comment]
+1

**Comment by githuesch** [comment]
I agree it would be nice to integrate Docker with OpsWorks, but it is more than just a change to our cookbooks. Therefore this is the wrong place to track this feature request. A better place is our forum, see https://forums.aws.amazon.com/forum.jspa?forumID=153.

**Comment by thomascramer** [comment]
I have submitted a feature request to AWS for this feature.  Though I think it would be good for others to also encourage OpsWorks to add integration with Docker.  Thanks.
