### ISSUE TITLE
Haproxy Cookbook Version is wrong

### ISSUE THREAD

**Issue by ryansch** [aws/opsworks-cookbooks#17]
I'm working on getting haproxy 1.5-dev17 installed so I can use some of the newer features.  In the process I realized that the haproxy cookbook in this repo doesn't match the installed cookbook on my haproxy LB instances.  In fact, the installed version already has functionality for specifying a different rpm to install.  Please update this repo.

**Comment by awsrequena** [comment]
we updated the cookbooks. Thanks for the hint.
