### ISSUE TITLE
OpsWorks Chef Default Encoding Issue (US-ASCII vs UTF-8)

### ISSUE THREAD

**Issue by mikegreiling** [aws/opsworks-cookbooks#173]
It would appear that the OpsWorks agent runs as user `aws` with no locale set.

I put the following in a custom cookbook and inspected the results:

```
puts 'Internal:'
puts Encoding.default_internal
puts 'External:'
puts Encoding.default_external
puts 'Locale Dump:'
puts `locale`
```

this produced the following in my log file:

```
Internal:

External:
US-ASCII
Locale Dump:
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

The problem with this is that rather than `UTF-8`, the ruby environment is set to `US-ASCII` and this breaks a few community cookbooks which happen to have unicode characters in their templates.

For instance, the **php-fpm** cookbook fails on me with the following message:

```
================================================================================
Error executing action `enable` on resource 'service[php-fpm]'
================================================================================


ArgumentError
-------------
invalid byte sequence in US-ASCII

...
```

In order to get around this, I've had to add the following to my custom cookbooks:

```
# fix for AWS default locale setting

if RUBY_VERSION > "1.9"
  Encoding.default_external = Encoding::UTF_8
end
```

While this works, I would really rather not have to resort to hacks to get my cookbooks working.  I think setting chef to run with UTF_8 encoding would be a pretty simple fix within the opsworks-agent source.

**Comment by ujuettner** [comment]
A fix will shipped with the next agent version.
