### ISSUE TITLE
Apache Config for passenger has AllowOverride None for http and AllowOverride All for https

### ISSUE THREAD

**Issue by halfbyte** [aws/opsworks-cookbooks#175]
Is there a reason for this discrepancy:

[AllowOverride None](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/passenger_apache2/templates/default/web_app.conf.erb#L21)
vs.
[AllowOverride All](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/passenger_apache2/templates/default/web_app.conf.erb#L92)

As the current templates don't allow for more fine grained access control (which I need) I'm trying to write .htaccess file on a before_restart hook, but this oddity keeps me from doing so. I would like to not override recipes for such a small issue :)

I believe, for a controlled environment like this, AllowOverride All is the correct solution.

I can of course provide a PR if that helps.

**Comment by wwwjscom** [comment]
+1

Anyone?  I'm having this issue too.  Ended up forking the whole repo just to make the `AllowOverride All` change.
