### ISSUE TITLE
Compile Error in PHP recipe

### ISSUE THREAD

**Issue by geminux50** [aws/opsworks-cookbooks#177]
Hi,
I have some problems with aws official chef recipes while deploying a php app via opsworks with Chef 11.10. It seems to be the same issue as for #140.
I had no problem yesterday...

Reproduce bug:
-> Fresh stack
-> No custom chef recipes
-> No json overrides
-> Fresh Ubuntu 14.04 LTS from amazon
-> No app to deploy
-> t1.micro instance

I opened a forum topic : https://forums.aws.amazon.com/thread.jspa?threadID=158000&tstart=0
# 
# Recipe Compile Error in /var/lib/aws/opsworks/cache/cookbooks/php/attributes/default.rb
## Chef::Exceptions::CookbookNotFound

Cookbook deploy not found. If you're loading deploy from another cookbook, make sure you configure the dependency in your metadata
## Cookbook Trace:

/var/lib/aws/opsworks/cache/cookbooks/php/attributes/default.rb:17:in `from_file'
## Relevant File Content:

/var/lib/aws/opsworks/cache/cookbooks/php/attributes/default.rb:

10:  #
11:  # Do NOT create an 'php/attributes/default.rb' in your cookbooks. Doing so
12:  # would completely override this file and might cause upgrade issues.
13:  #
14:  # See also: http://docs.aws.amazon.com/opsworks/latest/userguide/customizing.html
15:  ###
16: 
17>> include_attribute 'deploy'
18: 
19:  include_attribute "php::customize"
20: 

[2014-08-05T13:43:55+00:00] ERROR: Running exception handlers
[2014-08-05T13:43:55+00:00] ERROR: Exception handlers complete
[2014-08-05T13:43:55+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-08-05T13:43:55+00:00] ERROR: Cookbook deploy not found. If you're loading deploy from another cookbook, make sure you configure the dependency in your metadata
[2014-08-05T13:43:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jweiss** [comment]
Can you please post your OpsWorks stack ID and instance ID?

**Comment by geminux50** [comment]
stack id : 5eb95888-93f9-4622-98db-0962ad34676e
instance id : 0987f3f5-b0aa-405a-8f13-c4100448562c

**Comment by tlobinger** [comment]
Can you test if this is solved? It should. Thanks

**Comment by geminux50** [comment]
Solved! Thanks
