### ISSUE TITLE
unnecessary requirements in default opsworks_initial_setup cookbook

### ISSUE THREAD

**Issue by galaxy4public** [aws/opsworks-cookbooks#178]
There are currently 5 package_\* recipes in the opsworks_initial_setup cookbook (which is always enabled and cannot be overridden). All of these recipes are unnecessary since the mentioned packages will be installed as dependencies if necessary by the OS package manager.

Out of these 5 recipes, 3 are quite problematic (especially if you go with a "Custom Layer" and want to use your custom AMI):

package_sqlite.rb forcibly installs sqlite-devel - this brings all the development tools and development packages to the system.  It is quite sad to have that huge number of packages attracted to an instance which was configured as a clean server-only VM.

package_vim.rb installs vim-enhanced - this brings all vim's dependencies.  It's strange to have such a requirement defined in the default cookbook -- this is an interactive application and there should be no requirement for such a package in the default cookbook (e.g. I'm building a server with minimal set of packages and do not expect any interactive users to be logged into my server)

package_ntpd.rb - unconditionally installs the ntp package.  It's not nice to force a particular implementation of the NTP server onto users (e.g. this breaks chrony if a user wants to use it instead of ntp).

It would be really nice if the opsworks_initial_setup cookbook was handling the bare minimum required to support OpsWorks operations on an instance, this way the configuration of "Custom Layers" would be much more flexible.

**Comment by till** [comment]
:+1:

**Comment by nappa32** [comment]
:+1:

**Comment by awsrequena** [comment]
Thanks for your feedback. Unfortunately, we currently need this packages.  Vim is installed for convenience.

If you're using Chef 11.10, you could always overwrite the recipes you don't want to get processed with an empty files.  Use this with case.

**Comment by galaxy4public** [comment]
awsrequena, well, this is no a solution and not even a workaround since if we go this way it's like "a cat and a mouse" game.  The custom OpsWorks layer is supposed to be customisable with no whistles and bells attached, just the basic stuff to run the platform.  Yet, there are multiple things imposed on the user (the list of packages, which may be missing and not available on their custom AMIs), etc.

You said that a user can overwrite recipes -- this is true, what you didn't say that the recipes were created so inaccurately and non-modular that you can't just disable one - it will break lots of others.  Moreover, the cookbooks were created in the very same way.  Instead of using just one cookbook named, say, opsworks and keeping OpsWorks stuff under that namespace, whoever created the current convention decided that it would be funny to spread cookbooks with random naming conventions all over the place and make them mandatory.  So, one could not even predict when OpsWorks will break their stuff by introducing a cookbook clashing with the custom cookbook used by these people.

Well, I'm still very grateful for the introduction of such a service as OpsWorks -- I was able to build a system that doesn't depend on OpsWorks mandatory stuff at all (the only inconvenience left is the UI mentioning that XX cookbooks were defined by the system, when in fact they are not used on my instances).

I just thought that a bit of infrastructure design would help to make the system more flexible and robust.  Providing the community with a clean customisable "Custom Layer" would be a step forward to bringing enthusiasts like me into creating solutions using OpsWorks -- since this allows to use _any_ OS and build AMIs that can be managed by OpsWorks. Unfortunately, it seems we are not on the same page.

**Comment by till** [comment]
I agree that while it's possible to override cookbooks, it's also the number 1 source of breaks when updates come around. You technically do not want to touch any of it because it almost certainly break when you least expect it.

Closing this topic is a rather poor response.

**Comment by tlobinger** [comment]
We understood the problem and will address it. But we will not fix it _right_ now.

**Comment by jwieringa** [comment]
:+1: Would be great to have more flexibility especially when using custom layers.

**Comment by Swie** [comment]
:+1: This is mandatory for hardening the servers for production environments!
