### ISSUE TITLE
opsworks_shutdown fails (missing dependency?)

### ISSUE THREAD

**Issue by daveyeu** [aws/opsworks-cookbooks#179]
Hello,

I've been witnessing a custom shutdown recipe fail, but checking the logs, it looks like the `opsworks_shutdown` recipe is missing a `depends "opsworks_agent_monit"` line in its [metadata.rb](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/opsworks_shutdown/metadata.rb). Here's a snippet:

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache/cookbooks/opsworks_shutdown/recipes/default.rb
================================================================================


Chef::Exceptions::CookbookNotFound
----------------------------------
Cookbook opsworks_agent_monit not found. If you're loading opsworks_agent_monit from another cookbook, make sure you configure the dependency in your metadata


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache/cookbooks/opsworks_shutdown/recipes/default.rb:1:in `from_file'


Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache/cookbooks/opsworks_shutdown/recipes/default.rb:

1>> include_recipe "opsworks_agent_monit::stop"
2:  
```

**Comment by tlobinger** [comment]
You are right. If you are running 11.10 you can fix this yourself by overwriting the metadata.rb file with your own cookbooks (provide the file with the same file name at the same path). You should remove it as soon as we have the fix out to prevent future misbehaviour.

**Comment by daveyeu** [comment]
Awesome, thanks.

**Comment by tlobinger** [comment]
This is fixed. You can remove your overwrite.
