### ISSUE TITLE
Use a different method of health checks for node.js

### ISSUE THREAD

**Issue by martinheidegger** [aws/opsworks-cookbooks#186]
The current monit script does require the application to respond with a status 200 on / for node.js applications else it will restart the server. This is not documented and lead to a problem for me as my application didn't intend to serve anything on 200 and I wasn't aware that the monit script restarted my server. I think that a different sort of health check (i.e. process signals) might be a better solution. Specially since there are Node.js applications that run on a server but do not intend to serve a website (worker nodes or things like that)

**Comment by till** [comment]
@martinheidegger 
https://github.com/till/easybib-cookbooks/blob/master/opsworks_nodejs/templates/default/node_web_app.monitrc.erb

**Comment by martinheidegger** [comment]
@till Does not support domains and only supports health checks for port 80, not really fixing the problem.

**Comment by till** [comment]
@martinheidegger Just an example on how and where to override it. I implemented a health check for UDP on another port (for statsd).

**Comment by dancingfrog** [comment]
If any one still needs to reference the template provided by @till it's here: https://github.com/till/easybib-cookbooks/blob/e94ac7558f391ae39ac1454cb7717f92404060a2/opsworks_nodejs/templates/default/node_web_app.monitrc.erb
