### ISSUE TITLE
New env variable config fails on App without env vars set

### ISSUE THREAD

**Issue by STRML** [aws/opsworks-cookbooks#191]
When updating cookbooks, previously working apps fail to deploy due to the new environment var change. The error is:

```
Chef::Mixin::Template::TemplateError (undefined method `each' for nil:NilClass) on line #1:

1: <% node[:deploy][@app][:environment_variables].each do |key, value| %>
2: export "<%= key %>"="<%= value.gsub("\"","\\\"") unless value.nil? %>"
3: <% end %>
```

The issue is [this line](https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.10/deploy/attributes/deploy.rb#L101), which should also be renamed.

**Comment by evdevdev** [comment]
`[:deploy][@app][:environment_variables]` and `default[:deploy][application][:environment]` are two separate fields. The `environmental_variables` is part of the new OpsWorks feature described here: http://blogs.aws.amazon.com/application-management/post/Tx2G95J53SKI2E0/AWS-OpsWorks-supports-application-environment-variables

The `environment` variables are part of a default rails set up. It is not application specific. 

I think this confusion will keep coming up. @jweiss have you seen my comment about how `environment_variables` should be called `application_environment_variables` to prevent just this case?

**Comment by STRML** [comment]
I understand - then the real issue is that `[:deploy][@app][:environment_variables]` can be undefined, which should never happen. Where is it being set?

**Comment by evdevdev** [comment]
Somewhere inside of OpsWorks, I'd guess? We'll have to wait and see what they say.

**Comment by jweiss** [comment]
@STRML do you have an OpsWorks instance ID for me to look into?

The "environment" key will be no longer used in the cookbooks and we moved to "environment_variables".

node[:deploy][APP_SHORTNAME][:environment_variables] should be initialised by the OpsWorks backend to an empty hash.

**Comment by jweiss** [comment]
@STRML I see that this instance is now online after you updated your custom cookbooks. What did you change?

**Comment by STRML** [comment]
I changed the line linked to environment_variables.

Not the correct fix as mentioned but it does initialize the var.

**Comment by jweiss** [comment]
can you please do a 

$ opsworks-agent-cli get_json | grep environment

and send me the output. There :environment_variables should be initialised with an empty hash there

**Comment by jweiss** [comment]
From what I can see, you have an environment variable actually set, so the hash should be present in the JSON we send down.

So node[:deploy][@app][:environment_variables] should never be nil. Even if you initialise it with {} in a cloned version of our cookbooks. It should actually contain the hash you defined for your app. 

After a successful deployment, what is in the app.env file?

**Comment by STRML** [comment]
```
$ opsworks-agent-cli get_json | grep environment -C 3
    "frontend": {
      "application": "frontend",
      "application_type": "nodejs",
      "environment": {
        "NODE_ENV": "stage"
      },
      "environment_variables": {
        "NODE_ENV": "stage"
      },
      "auto_bundle_on_deploy": true,
--
      "opsworks_cleanup"
    ]
  },
  "chef_environment": "_default",
  "recipes": [
    "opsworks_custom_cookbooks::load",
    "opsworks_custom_cookbooks::execute"
```

The JSON looks fine to me. I could try reverting the cookbook change I made and seeing if I can replicate the error. 

`app.env` contains (mostly because of my hack from 'environment' to 'environment_variables'):

```
export "RAILS_ENV"=""
export "RUBYOPT"=""
export "RACK_ENV"=""
export "HOME"="/home/deploy"
export "NODE_ENV"="stage"
```

**Comment by STRML** [comment]
@jweiss I went ahead and backed out the cookbooks change that I made. Output from `opsworks-agent-cli get_json | grep environment` is the same as above, but I still see this:

```
Chef::Mixin::Template::TemplateError (undefined method `each' for nil:NilClass) on line #1:

1: <% node[:deploy][@app][:environment_variables].each do |key, value| %>
2: export "<%= key %>"="<%= value.gsub("\"","\\\"") unless value.nil? %>"
3: <% end %>

(erubis):1:in `block in evaluate'
```

**Comment by awsrequena** [comment]
are you using any custom cookbook or custom JSON? and how many apps are defined in your stack?
