### ISSUE TITLE
Apache user and group configuration in apache2.conf.erb both set to node[:apache][:user] attribute

### ISSUE THREAD

**Issue by nicholas-coker** [aws/opsworks-cookbooks#196]
According to http://docs.aws.amazon.com/opsworks/latest/userguide/attributes-recipes-apache.html#attributes-recipes-apache-group, one can configure the apache user and group by setting the node[:apache][:user] and node[:apache][:group] settings, respectively. However, in the cookbook template file apache2.conf.erb, the apache user and group are both set equal to node[:apache][:user], meaning that the group setting will never take effect.

Is this intentional?

**Comment by awsrequena** [comment]
You're right! thx

**Comment by awsrequena** [comment]
Fixed. 

Will come with the next agent release.
