### ISSUE TITLE
s3 deployment: extract fails

### ISSUE THREAD

**Issue by till** [aws/opsworks-cookbooks#197]
Deployment completes, but the archive is not extracted:

```
root@app1:/srv/www/management# /opt/aws/opsworks/current/bin/extract /srv/www/management/releases/20140825191245/archive /tmp/
unhandled archive format '/srv/www/management/releases/20140825191245/archive: POSIX tar archive (GNU)' - not extracting
root@getcourse-app1:/srv/www/management# echo $?
0
```

I backtracked this call through the cookbooks and manually executed it.

Kind of surprised an error has `exit=0` and doesn't fail the deployment.

The `.tar` file is created on Linux and extracts fine on OSX.

**Comment by till** [comment]
Related: https://forums.aws.amazon.com/thread.jspa?messageID=558420

**Comment by till** [comment]
Documentation says, a tarball should work:
http://docs.aws.amazon.com/opsworks/latest/userguide/workingapps-creating.html#d0e9841

**Comment by awsrequena** [comment]
Hi Till,  this is no error. The `extract` script only handles compressed files, the message:

`unhandled archive format '/srv/www/management/releases/20140825191245/archive: POSIX tar archive (GNU)' - not extracting`

only says, that the file was not processed. In this case, not decompressed.

About the documentation, you're right. We don't handle uncompressed tar files, we need to correct this.

**Comment by till** [comment]
@awsrequena the error is that my deployment completed successfully even though it _did not work_.

**Comment by awsrequena** [comment]
That is also a bug, we should fail at some point and not just go forth.

I marked this issue as a Bug, we're bringing it into our backlog and will solve it as soon as possible.

Till, thanks a lot for bringing this up.

**Comment by awsrequena** [comment]
could you post some logging that shows that the app wasn't deployed without a failure a message?

**Comment by till** [comment]
@awsrequena No, I can't go back long enough, we deployed like 50 times since I opened this. We do CD and OpsWorks doesn't allow me to go back far enough enough.

All I know is, I ended up with a file called "archive" in `/srv/www/app-name/current` which was the tar, without the extension (`.tar`).

**Comment by till** [comment]
My artefact was not called `archive` though it was `appname-x.y.z.tar`.

**Comment by githuesch** [comment]
```
    remote_file "#{tmpdir}/archive" do
      source archive_url
      retries 2
    end
```

That's how we download. So on disk it's called archive, no matter what the original name was.
