### ISSUE TITLE
Split out cookbooks?

### ISSUE THREAD

**Issue by patcon** [aws/opsworks-cookbooks#2]
Hey guys, thanks for sharing all of these, but any chance you can split them out? I think that's now the official opscode recommendation :)

**Comment by patcon** [comment]
Or even using a Cheffile via librarian so that we know where the community ones are coming from at a glance. It looks like some of these are community cookbooks, but all the context and history are lost. Would be great to see all these awesome cookbooks treated like packages and managed similarly! Thanks again

**Comment by richleland** [comment]
I completely agree. Librarian or Berkshelf would be great. For my own OpsWorks repo I'll have to run Librarian, commit the collected cookbooks, push, update cookbooks on OpsWorks, etc. Ideally I'd like to get rid of that "commit the collected cookbooks" part of things.

**Comment by ryansch** [comment]
Also agree.

**Comment by ryansmith3136** [comment]
:+1:

**Comment by hd-deman** [comment]
:+1: +1

**Comment by dbachelder** [comment]
+1. We had to write our own system for converting a Berkshelf managed set of cookbooks into a OpsWorks s3 managed bag of cookbooks... it works well, but it would be nice not to own an entire code line / process for this

**Comment by hd-deman** [comment]
@dbachelder, is yours system public?

**Comment by ryansch** [comment]
@hd-deman Here's my solution: https://github.com/aceofsales/opsworks-control-tower

**Comment by jamesonjlee** [comment]
I think the other major issues are the old cookbooks that take up the common namespace as well (nginx, apache, deploy, ruby, ...)

**Comment by patcon** [comment]
Librarian allows renamespacing, if that's what you mean? It doesn't necessarily need to be on the chef community site to follow best-practice a little bit better :)

``` rb
cookbook "nginx",
  :github => "aws-cookbooks/nginx", # or "aws/opsworks-nginx" or whatever
  :ref => "v1.0.0"
```

**Comment by jamesonjlee** [comment]
I do that for me (berkshelf), but there is already an nginx cookbook and I have seen my local nginx cookbook get ignored (and so I have to namespace my local nginx, etc. etc.) part of this is because I am running custom.... blah blah

but this repo really should be split and managed as separate repos...

**Comment by HelloGrayson** [comment]
Has anyone written a workflow post on how to use berkshelf with opsworks yet? Thanks...

**Comment by hd-deman** [comment]
Any updates? I really need to know is this will be implemented and if so what solution will be used.

**Comment by HelloGrayson** [comment]
I really want to use opsworks but I cringe at the thought of using a single repo...

**Comment by jsierles** [comment]
Also would like this for use with Berkshelf.

**Comment by shlomoswidler** [comment]
You can pull in individual opsworks cookbooks from the github repo with the following syntax in your Berksfile:

```
cookbook 'apache2', github: 'aws/opsworks-cookbooks', branch: 'master-chef-11.4', rel: 'apache2'
```

**Comment by patcon** [comment]
Man, I really just wish `Berksfile`s and `Cheffile`s were cross-compatible...

**Comment by josh-wrale** [comment]
+1.. Looking for a working tutorial to use Berkshelf + GitHub for OpsWorks

**Comment by runemadsen** [comment]
+1

**Comment by bbergstrom** [comment]
+1

**Comment by jweiss** [comment]
closing as this is a very old issue
