### ISSUE TITLE
Update Default Branch to release-chef-11.10

### ISSUE THREAD

**Issue by mikegreiling** [aws/opsworks-cookbooks#200]
Minor issue, simply as a matter of convenience... shouldn't the default branch on GitHub be the the chef 11.10 branch?  I keep coming here for reference and have more than once gotten confused looking at a different version of a recipe.  Seeing as 11.10 is (or appears to be) the current default for new OpsWorks stacks, it would seem prudent to make this branch front and center when people come here to reference the built-in cookbooks.

**Comment by githuesch** [comment]
Good point, done.
