### ISSUE TITLE
haproxy stats is only accessible via HTTP (not HTTPS)

### ISSUE THREAD

**Issue by D1plo1d** [aws/opsworks-cookbooks#203]
It would be preferable if the haproxy stats page was served via HTTPS. Presently, it appears that the app server will override the stats page and I am left at an nginx 404 page when I try to go to my haproxy stats url via HTTPS (I don't want to send my haproxy password over plain text).

Is it possible to patch the configuration so that the haproxy stats url takes precedence over all others?

**Comment by fh** [comment]
@D1plo1d haproxy on Opsworks is still 1.4.x (at least with the ubuntu precise images), which does not have any https support. If there is something listening on HTTPS (elb, some nginx wrapper?), you should check the configuration there if the stats-page url actually ends up at haproxy. 
This works like a charm in our stack setup.

**Comment by D1plo1d** [comment]
Yeah, that makes sense, I'll just reverse proxy it through nginx. Cool. Thanks!
