### ISSUE TITLE
Builtin mysql cookbook is inappropriately named

### ISSUE THREAD

**Issue by benlangfeld** [aws/opsworks-cookbooks#211]
In order to manage databases in my custom cookbooks I use [the `database` cookbook](https://supermarket.getchef.com/cookbooks/database), which depends on [the true `mysql` cookbook](https://supermarket.getchef.com/cookbooks/mysql) `>= 5.0.0`, for which I get v5.3.6. This all resolves fine using Berkshelf locally in test-kitchen.

In my staging environment, `opsworks-cookbooks` then goes ahead and injects [its own replacement for the `mysql` cookbook](https://github.com/aws/opsworks-cookbooks/tree/release-chef-11.10/mysql) at version 1.0.0, causing a conflict in the versions of the cookbook available and expected. My Chef run completely fails to start.

As long as OpsWorks keeps injecting its version of `mysql`, I see no way to resolve this. Is there any way I can prevent this injection? Why is the custom cookbook named so inappropriately as to wipe out a publicly available cookbook, rather than being named `opsworks_cookbook`?

**Comment by githuesch** [comment]
That's true, and it's really not a new issue. The same is true for all our cookbooks that match the name of any community cookbook. We always had those cookbooks in there, and with the addition of Berkshelf support, this started to become a big problem. We can't easily fix this for an existing Chef version in AWS OpsWorks, but will have to fix it when we start supporting a new one. Sorry for the inconvenience.

**Comment by benlangfeld** [comment]
What is the proposed solution to allow people to use the true `mysql` cookbook? Could you please explain why this can't be fixed for the existing Chef version? Why is a simple rename not possible?

Alternatively, why is it not possible to remove recipes from the set of built-ins in the OpsWorks UI? Even a custom layer includes your mysql cookbook. In my book, a "custom" version of something should come blank...

**Comment by githuesch** [comment]
It's fair to assume that a custom layer doesn't come with any preset cookbooks. However, in AWS OpsWorks, some defaults have always been there. For some customers this is a problem. Fixing it for those customers might turn it into a problem for all the other customers. We have no way to detect which customers consume our built-in cookbooks from their own ones, using include_attribute, include_recipe, and so on.

The proposed solution is to wait for us to fix this.

The reason we only tackle such changes in new Chef versions is that this way there can't be any existing customers that we break.

**Comment by drazen** [comment]
There has to be a better solution than "wait".   

I second the call for at least the ability to remove or disable the opsworks builtin cookbooks.  This would give us a clean way around this bug, without risk to your existing customers.

In the case of 'database' cookbook, my workaround was to replace the mysql dependancy in the generated metadata.json file produced by 'berks vendor.." with "depends 'mysql', '>= 1.0.0'

A hack, but at least I dont have to fork the 'database' cookbook

**Comment by shlomoswidler** [comment]
Here is an early version of my workaround to this issue: the Tabula Rasa cookbook.

https://github.com/shlomoswidler/tabula_rasa

Run community cookbooks from within AWS OpsWorks without clashing with the older versions in opsworks-cookbooks. Recipes run from within Tabula Rasa will not have access to the opsworks-cookbooks (unless you include them in your repository) but they will see your Custom Stack JSON and all the Ohai settings added by the AWS OpsWorks Agent.

Version 0.1.0 has only been tested with Chef 11.10, on Ubuntu 12.04, and only supports Git and SVN repositories.

This won't prevent OpsWorks recipes from running, but it will give you an isolated environment in which you can run community cookbooks without worrying about the name and version conflicts with opsworks-cookbooks.

**Comment by benlangfeld** [comment]
@shlomoswidler You've not included an accepted open-source license in your project, and you've stated in the readme "Licensed for non-commercial use only.". In the cookbook metadata you've included copyright in the license field, and these are totally separate things. Could you possibly clarify the license the cookbook is offered under?

**Comment by shlomoswidler** [comment]
Thanks for pointing that out @benlangfeld. It's Apache 2.0, and corrected now.

**Comment by steve9001** [comment]
Wow, this is a real deal-breaker. Doesn't this mean that anybody who uses community cookbooks cannot use OpsWorks?

 Is there any sense of the priority to get this resolved? For example releasing a new version of `opsworks-cookbooks` that has all cookbooks renamed with `opsworks-` prefix and adding a switch in the console to use the new versions? That would prevent breaking existing customers setups who somehow depend on the built-in cookbooks' names.

**Comment by benlangfeld** [comment]
> Wow, this is a real deal-breaker. Doesn't this mean that anybody who uses community cookbooks cannot use OpsWorks?

Only those small number of cookbooks which have name collisions, but several of these are very widely used and central to people's Chef usage. It is rather disastrous when you run into it.

**Comment by aik099** [comment]
The `apache2` package for example :( The version used under opsworks is quite outdated and I can't use newer version because of name collision.

**Comment by RLovelett** [comment]
Agree with @steve9001. This just seems too crazy to be true. :rage1: 

While I was trying to debug this and come up with a resolution I kept saying to myself: "There is no way they would provide a name collision with the publicly shared cookbook. So I'll just change my dependency on `mysql` to theirs." I was gobsmacked to find out that the **_default**_ `mysql` cookbook is completely different and yet has the same name.

I can appreciate not breaking existing configs. Though as @githuesch pointed out we should at least be able to remove the defaults in a "custom" build.

**Comment by jweiss** [comment]
We will namespace our cookbooks with the next Chef release we do. This will hopefully fix this issue for good.

**Comment by aik099** [comment]
@jweiss , so we need to wait for next Chef release to see renamed cookbooks?

**Comment by jweiss** [comment]
@aik099 Yes as we would otherwise break customers relying on the existing name. Switching Chef versions in AWS OpsWorks is an explicit change triggered by the user so we can have incompatible changes in there.

**Comment by waj** [comment]
Any estimate when the rename is going to happen? This is blocking me from adopting AWS OpsWorks right now :(

**Comment by franklinwise** [comment]
@jweiss - Why can't you just allow customers to delete recipes from the built in section and allow the Berksfile to override and point to a specific cookbook using the github directive.

**Comment by minusdavid** [comment]
I recently ran into this issue as well. When I tried using the Opsworks 'mysql', I got fatal errors on my machine. When I tried using the community 'mysql', the collision between the two cookbooks was even more catastrophic.

Trying to figure out some workarounds, but rather annoyed... I'd wondered a bit about how Chef and the community would handle competing names... although I suppose this is an Opsworks issue more than anything.

**Comment by minusdavid** [comment]
@jweiss waiting for a new Chef version makes a lot of sense. Are there any estimates about when AWS might support a new version of Chef with OpsWorks namespaced cookbooks?

**Comment by ErikDahlinghaus** [comment]
Bumping this issue because it is causing me trouble right now.

**Comment by githuesch** [comment]
Please check out [our launch announcement](https://forums.aws.amazon.com/ann.jspa?annID=3397) for Chef 12 Linux. Built-in cookbooks like `mysql` or `apache` that previously caused clashes with community cookbooks are not namespaced, but completely removed. The announcement links to our documentation for getting started with this clean, new approach.

**Comment by kellytehuna** [comment]
Is there are proposed release date for Linux-based instances?

**Comment by jweiss** [comment]
@kellytehuna Chef 12 for Linux was launched in December: https://blogs.aws.amazon.com/application-management/post/Tx1T5HNA1TSU8NH/AWS-OpsWorks-Now-Supports-Chef-12-for-Linux

**Comment by kellytehuna** [comment]
@jweiss Oh! I see I misread. I guess I will have to create a new stack in OpsWorks. Thanks!
