### ISSUE TITLE
Amazon Linux 2014.09 supports PHP 5.5. Update recipes to support new version

### ISSUE THREAD

**Issue by buzzedword** [aws/opsworks-cookbooks#218]
While the current chef recipes support PHP 5.5 on Ubuntu boxes, the Amazon Linux recipes are woefully using 5.3. With the advent of 2014.09 supporting PHP 5.5, and the onset of 2015.03 which removes support for PHP 5.3, 5.4, we direly need an officially sanctioned PHP 5.5 solution.

**Comment by aik099** [comment]
In https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/mod_php5_apache2/attributes/default.rb file versions of used packages are hardcoded. It would be great to have PHP version dropdown somewhere on PHP layer configuration page and then it's value will go into corresponding package names.

For Amazon Linux PHP 5.4 package is called "php54", PHP 5.5 is called "php5.5" and PHP 5.3 is called "php".

Unfortunately for Ubuntu it isn't that easy to get past PHP versions.

**Comment by aik099** [comment]
I've made few PR's that might help:
- #243 - use PHP 5.4 all the time, but I don't know how to make it configurable in layer settings, because PHP version is shared across several cookbooks (mod_php_apache2, apache2)
- #242 - update to use Apache 2.4, which supports PHP 5.4

**Comment by yoshiwaan** [comment]
I would really like to see an update on this. php 5.3 is end of life: http://php.net/eol.php
I know you can't just alter the existing AL 2014.09.2 default to php5.5 but nor should there be a wait until the next AL update where (presumably) the default php packages are 5.5.

Really, a dropdown selection like Ruby would be ideal (so long as people get a fair warning that the Apache version will change to 2.4 if you do so).

**Comment by jbdevprimary** [comment]
This is still (and becoming more so) a real and prevailing problem with this and other Opsworks cookbooks. PHP-FPM is equally useless, hardcoded to PHP 5.3. Really need to see an update on this issue!

**Comment by aik099** [comment]
I've installed REMI repo with higher priority then Amazon repo. This way I was able install any needed PHP version using same package name, that used for PHP in AWS cookbooks.

**Comment by yoshiwaan** [comment]
The latest (2015.03) version of amazon linux came out, PHP5.3 is still the default and PHP5.6 has been added as another alternative.

Of course it's possible that users can write cookbooks to alter the default cookbooks but for something this base level I really feel it should be a part of the base cookbooks.

**Comment by nathanlenz** [comment]
Please make this a feature, would love to be able to choose my PHP version at the Layer level.

**Comment by yoshida** [comment]
I created cookbooks supporting for PHP 5.6 and Apache 2.4 and PHP Application deployment.
Please try it:
- https://github.com/yoshida/httpd24_php56_opsworks

But, I want to be able to choose PHP version at the Layer settings...

**Comment by humbletiger** [comment]
+1000

Would be __WONDERFUL__ to choose PHP version at the Layer level.

**Comment by panbanda** [comment]
+1

**Comment by yoshiwaan** [comment]
Considering the newer versions of Opsworks don't have pre-baked recipes at all I doubt this will happen. I think your best bet would be to use a Chef 12 stack and create your own recipe to install the version of php you want using the php cookbook: https://supermarket.chef.io/cookbooks/php
Using the following attributes in a php wrapper cookbook and having the php::default recipe in your run list you can get php5.5 easily:

```
default['php']['version'] = '5.5.33'
default['php']['install_method'] = 'source'
```

Plus you can test it locally in Test Kitchen unlike with the old Opsworks recipes.
