### ISSUE TITLE
Unable to setup or deploy php apps after adding support for environment variables

### ISSUE THREAD

**Issue by fillup** [aws/opsworks-cookbooks#228]
In `mod_php5_apache2/templates/default/web_app.conf.erb` it was updated to loop through `@environment` to place environment variables into the file. However if `@environment` is not defined it crashes out and prevents instances from starting and apps from deploying. 

After this release multiple stacks of mine started having problems launching new instances, I've finally traced it back to this. L41 needs to be updated to test if `@environment` is defined and is a hash before attempting to iterate on it. I assume this is a very simple fix but I suck at ruby.

See: https://github.com/aws/opsworks-cookbooks/blob/f9b30f22defd3ec88854172b778e8ac7bfef1c93/mod_php5_apache2/templates/default/web_app.conf.erb#L41-L43

The error I get during setup or deploy is:

```
Chef::Mixin::Template::TemplateError (undefined method `each' for nil:NilClass) on line #41:

41:   <% @environment.each do |key, value| %>
42:   SetEnv "<%= key %>" "<%= value %>"
43:   <% end %>
```

**Comment by tlobinger** [comment]
do you have an open support case or want to share your stack ID so that we can investigate?

**Comment by fillup** [comment]
This specific issue seems to have been fixed in a later update, thanks for the response.

**Comment by firecentaur** [comment]
Hi there, I also am experiencing this - I can not start up any instances, it complains about  <% @environment.each do |key, value| %>
SetEnv "<%= key %>" "<%= value %>"
  <% end %>

how can I fix this?
