### ISSUE TITLE
runit cookbook not working on Amazon Linux

### ISSUE THREAD

**Issue by crowdmatt** [aws/opsworks-cookbooks#23]
The runit cookbook doesn't support Amazon Linux, so when you run it on AL, it just fails silently.  runit package won't be installed at all.

**Comment by richid** [comment]
+1. This is a pretty egregious bug. It's also several versions back; the Opscode version (https://github.com/opscode-cookbooks/runit) is at 1.1.2.

**Comment by crowdmatt** [comment]
FWIW it _does_ work on ubuntu

**Comment by richid** [comment]
I got it working by replacing the AWS version with the Opscode version and tweaking a couple attributes. However, as you mentioned, Ubuntu currently works so I'll just stick with that for the time being.

**Comment by jayTandalai** [comment]
@richid I tried configuring opscode's runit in my Berkshelf but Opsworks keeps resolving back to it's default runit for some reason on amazon linux ami. Can you tell me how you got this working. Thanks

**Comment by awsrequena** [comment]
We deprecated support for this cookbook with the introduction of Chef 11.10
