### ISSUE TITLE
Rack / Unicorn Error - ActiveRecord can't connect

### ISSUE THREAD

**Issue by gplz** [aws/opsworks-cookbooks#236]
I am using a rack app with ActiveRecord and it will work fine if I comment out the connection attempt in the unicorn.conf. My database.yml is being correctly created and the app is function once I remove the line below. I have tried preload_app = true and false with no luck. Is there something I need add to my app to get preload_app working and the following not to fail?

https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/unicorn/templates/default/unicorn.conf.erb
I am getting 
ERROR -- : 'default_env' database is not configured. Available: [](ActiveRecord::AdapterNotSpecified)
until i comment out the following: (line 50)

``` ruby
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.establish_connection
  end
```

**Comment by ypadlyak** [comment]
@gplz have you resolved it somehow?

**Comment by ypadlyak** [comment]
@gplz Just fixed, upgrades activerecord. The latest version makes use of RACK_ENV variable to look up current environment. I believe the issue could be closed now.
