### ISSUE TITLE
Allow replacing base cookbooks

### ISSUE THREAD

**Issue by aik099** [aws/opsworks-cookbooks#245]
Please allow replacing of base cookbooks or at least recipes in them. If I find a bug in base recipe that is used across several other base cookbooks, then it's near to impossible to fix a recipe without replacing all of base cookbooks where it's used.

**Comment by aik099** [comment]
@jweiss , can you please look at this?

**Comment by jweiss** [comment]
With our Chef 11.10 integration you are able to override recipes, attribute files, templates etc. 

We will gladly merge simple bug fixes. It is a little bit more difficult with more complicated changes due to the potential impact on customers.

Do you have a specific example of what you need to do?

**Comment by aik099** [comment]
> You cannot override a built-in recipe by implementing a custom recipe with the same cookbook and recipe name. For each lifecycle event, AWS OpsWorks always runs the built-in recipes first, followed by any custom recipes. Because Chef does not run a recipe with the same cookbook and recipe name twice, the built-in recipe takes precedence and the custom recipe is not executed.

That's what documentation at http://docs.aws.amazon.com/opsworks/latest/userguide/customizing.html says. So only attribute and template files can be overridden, but no recipes. That is very bad because if I discover critical bug I need to fix in recipe or another change I need to make, then I need to wait for new base cookbook version to be released with a fix, but unfortunately in business you can't really sit and do nothing :(

> Do you have a specific example of what you need to do?

My Stack URL: https://console.aws.amazon.com/opsworks/home?region=us-west-2#/stack/efe28abd-dcfc-4262-809e-3ebaa950b6b4/stack

I wanted to change condition (see https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/apache2/recipes/mod_php5.rb#L26-L30) used to detect if PHP needs to be installed or not. Right now the `php` package (the Apache module) is only installed when PHP CLI binary is not present. So if I install `php-cli` package first (and if that package don't have dependency on `php` package, which is the case when Remi repository is used), then Apache PHP module is never installed. I've also reported that problem separately in #244.

**Comment by githuesch** [comment]
@aik099 The documentation page you're referring to applies for Chef 0.9 and 11.4.
See http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html#workingcookbook-chef11-10-override for how overrides work in Chef 11.10 in AWS OpsWorks. @jweiss is right, recipes can indeed be overridden.

**Comment by aik099** [comment]
Thanks.

@githuesch , That is a bit confusing indeed. The first thing you hit in Google is that URL I mentioned. On it it's nowhere written that it's Chef version specific documentation page or if there is another page about same topic.

@jweiss , I recommend updating that note in general documentation saying, that build-in cookbooks now can be overwritten safely since Chef 11.10 and putting link to page you just gave me.

**Comment by grampajoe** [comment]
The method in http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html#workingcookbook-chef11-10-override is problematic, for a few reasons:
- It's hard to test overridden files. We'd have to re-implement the merging process OpsWorks uses.
- Overridden files need to be kept up-to-date manually. There's no sustainable way to track changes to every file, especially in a timely enough manner to prevent breakages with many automatic Chef runs per day.

Aside from those issues, overriding individual files has a lot of the same downsides as forking cookbooks, which the Chef community has put a lot of work into moving away from. My strong suggestion is to allow the wrapper cookbook pattern to override base cookbooks.
