### ISSUE TITLE
rails cookbook: database.yml dangerous environment creation

### ISSUE THREAD

**Issue by ilyakatz** [aws/opsworks-cookbooks#246]
The cookbook for rails database.yml creates misleading configuration

Currently in production, this file

https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/rails/templates/default/database.yml.erb

will create a configuration that will allow someone to 1) login to production 2) run rails console in development mode 3) but still connect production database.

This is pretty misleading and dangerous.

**Comment by k0nserv** [comment]
Great fix :) :+1:

**Comment by fred** [comment]
if you want best security, just delete the database.yml once server is started.
you dont need it after that. re-deploy app if server is rebooted.
we do this for PCI-DSS requirements.

**Comment by fredrik** [comment]
:+1:  for merging @ilyakatz's fix

**Comment by chrisnicola** [comment]
@ilyakatz I'm a bit confused, if they can log into productions what is stopping them from running rails console in production mode? Or just running `sudo su deploy`? I'm asking because I'm just testing out OpsWorks and I'm trying to understand the severity of this issue.

**Comment by ilyakatz** [comment]
@chrisnicola the problem is not that people on production can run production console but that people logging into **production** can run `rails console staging` accidentally and it will still be on production. So it will misleading and can cause major problems

**Comment by ilyakatz** [comment]
@fred your suggestion will only work if you have just the web server, what if there are backend processes running that need to connect to database? or if there are monitoring processes that startup a process when it goes down?
