### ISSUE TITLE
[Feature Request] Recipe for Memcached Restart/Flush

### ISSUE THREAD

**Issue by ggedde** [aws/opsworks-cookbooks#251]
Would be nice if there was a recipe to restart memcached in the memcached cook books.
Yes, I can create my own, but would nice if it was already there.

I need this as in AWS Opsworks I would like to restart memcached on a Deploy cycle so it would clear the cache.  Or at least have a way to clear or flush the memcached service.

**Comment by aik099** [comment]
There was no much activity on the repo recently. Yes, people do ask things and submit PR's, but none of them was merged in past month. I wonder if guys from Amazon AWS are still interested in supporting this repo :(

**Comment by ggedde** [comment]
No worries,
AWS is using the memcached cook book for its Memcached Layers. it just doesn't having any recipes tied into Deploys.  

So I created my own.

```
# restart Memcached service to flush cache
service "memcached" do
   action :restart
end
```

Would be nice it that was just already available though  (memcached/recipes/restart.rb)

**Comment by aik099** [comment]
That's good to hear.

Are you deploying a PHP application? If so, then how you dealt with problem that PHP 5.3 is installed on `Amazon Linux` AMI.

**Comment by jweiss** [comment]
@aik099 unfortunately we have been very busy. We are still very interested in PR for this repo.

As for PHP, on Ubuntu 14.04 LTS we use PHP 5.5.

**Comment by aik099** [comment]
@jweiss , thanks for the info, but I'm using `Amazon Linux AMI` and my application requires PHP 5.4 to run. To make this work I hard to connect Remi repo with same priority as built-in AWS yum repo.

**Comment by fred** [comment]
@jweiss, honestly, it looks likely that there is no real interest in PR for this repo, 
There are PRs accumulated for many months, and critical issues not being fixed and still left there. 
Opsworks is just adding features, but not fixing any bugs or adding improvements from PRs.
Quite disappointing. I have so many custom cookbooks that are actually just fixing bugs on Opsworks cookbooks.
