### ISSUE TITLE
[bug] mysql cookbook can't work with RDS mysql 5.6 version

### ISSUE THREAD

**Issue by ops-dev-sh** [aws/opsworks-cookbooks#253]
Please update your mysql cookbook to support 5.6 version (both server and client).

Current will install 5.5 version of mysql client even if RDS use 5.6 server version.

Please fix.

**Comment by aik099** [comment]
:+1: , I've changed Yum repo to Remi so that latest `mysql` package is installed.

**Comment by ops-dev-sh** [comment]
But I use Ubuntu 14.04. `package mysql-server` and `package mysql-client` will install 5.5

**Comment by ops-dev-sh** [comment]
OS: ubuntu 14.04

Since there are hard code part `node[:opsworks][:layers].has_key?('db-master') || (node[:opsworks][:stack][:rds_instances].any?{|rds_instance| rds_instance[:engine] == 'mysql'})` in `recipe[mysql::client]`

The recipe `mysql::client` in setup of Opsworks will simply fail if you have mysql client version 5.6 installed.

``` ruby
if node[:opsworks][:layers].has_key?('db-master') || (node[:opsworks][:stack][:rds_instances].any?{|rds_instance| rds_instance[:engine] == 'mysql'})
  Chef::Log.info 'Detected a db-master layer or at least one MySQL RDS DB instance - making sure the MySQL client is installed'
  include_recipe 'mysql::client_install'
else
  Chef::Log.info 'No db-master layer or MySQL RDS DB instance found. Skipping MySQL client package installation.'
end
```

**Comment by curiosity26** [comment]
Yea this is horribly frustrating. I was hoping I could force the :environment_variables via the custom JSON parameter on the Stack Settings. But no luck. Looks like I'll have to rebuild the stack using Chef 11.04 because obviously no one is going to merge this request or implement some other sort of fix. It's been over 6 months and the problem still exists.

**Comment by noboomu** [comment]
Any word on this? mysql::client built-in recipe causes setup to fail.

**Comment by ganeshfreshdesk** [comment]
It fails with aurora as well
