### ISSUE TITLE
Deploy Migration `environment` Can Be nil

### ISSUE THREAD

**Issue by noazark** [aws/opsworks-cookbooks#255]
You'll see [here](https://github.com/aws/opsworks-cookbooks/commit/7c1a659707a5c335b3c25c49ec0217c77796ac2c#diff-a7e8b61380c1485691d1fc718cb6a255R35) that `environment` may be `nil`, I assume that is an OpsWorks thing. So, shouldn't `environment` be tested for `nil` on [line 40](https://github.com/aws/opsworks-cookbooks/commit/7c1a659707a5c335b3c25c49ec0217c77796ac2c#diff-a7e8b61380c1485691d1fc718cb6a255R40) as well?

Should look like this?

``` rb
if environment && environment.has_key?("SHOW_ENVIRONMENT_VARIABLES")
  Chef::Log.info "#{@new_resource} migrating #{@new_resource.user} with environment #{env_info}"
else
  Chef::Log.info "#{@new_resource} migrating #{@new_resource.user}"
end
```

**Comment by noazark** [comment]
This is related to a post I made earlier in the AWS forums. https://forums.aws.amazon.com/thread.jspa?messageID=585401

**Comment by noazark** [comment]
@jweiss can someone please take a look at this? I believe it is responsible for breaking all deployments on my stack and therefore all new instances as well.

**Comment by ujuettner** [comment]
Thanks for pointing this out. We'll ship a fix with the next agent version.
In the meantime, I'd recommend setting a dummy environment variable on your app to unblock you.

**Comment by noazark** [comment]
Please don't blow this off like it's a minor issue. All app deployments are failing (even those w/o a migration) and therefore all new instances fail during "running_setup". Is >72 hours of downtime acceptable?

On Friday, when I found the issue in your code I attempted to get around it by setting a bunk environment variable, that did not work. I also attempted to circumvent the issue by setting the resource's "environment" to `{}` so at least it would not be nil, that did not work either. Please fix this, and stop overloading other peoples code, unless you're willing to fix what you break.

FWIW, I will fully accept responsibility if it's something that I'm doing wrong, but at this point it appears that this issue that I am having is completely on the shoulders of OpsWorks.

**Comment by noazark** [comment]
And, thank you for the response, I did try to set up a dummy environment variable again for all our apps as you suggested. But, as I mentioned, that didn't work the first time I tried it and is not working again. If you'd like any more details about the stack I'd be happy to provide, just hit me up: noah@billysbilling.com

**Comment by ujuettner** [comment]
I saw you posted the instance ID in the AWS OpsWorks forum. With that we were able pull the whole Chef log indicating that you're using the deploy resource directly without passing an environment. So, as a workaround I recommend passing a hash as environment to that deploy resource:

```
deploy "..." do
  ...
  environment {}
  ...
end
```

We will fix this with the next agent version.

**Comment by noazark** [comment]
I feel like I'm repeating myself. Well, I am repeating myself. In both this issue (right up above, where you should have read) and in the forum linked I mentioned:

> I also attempted to circumvent the issue by setting the resource's "environment" to {} so at least it would not be nil, that did not work either.

The exact patch I made (on Friday) was:

``` diff
deploy deploy_config[:deploy_to] do
+ environment {}
```

That did not work. Seriously, stop blowing this off. "the next agent version" is a terrible response to a problem that is a) right in front of you, and b) is breaking your entire product. Right now if one of our instances were to fail we would be completely lost. My time would be better spent moving our code off OpsWorks right now than trying to wrangle you in to do your jobs, so its your call.

**Comment by noazark** [comment]
For your amusement, instance 50e9991f-6821-4f12-94c4-7ca172f19c1d:

```
================================================================================
Error executing action `deploy` on resource 'deploy[/srv/www/<redacted>]'
================================================================================


NoMethodError
-------------
undefined method `has_key?' for nil:NilClass


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_commons/libraries/monkey_patch_deploy_provider.rb:40:in `block in migrate'
/var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_commons/libraries/monkey_patch_deploy_provider.rb:39:in `migrate'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/billy/definitions/billy_deploy.rb

45:       deploy deploy_config[:deploy_to] do
46:         environment {}
47:         repository deploy_config[:scm][:repository]
48:         user deploy_config[:user]
49:         group deploy_config[:group]
50:         revision deploy_config[:scm][:revision]
51:         migrate !params[:migration_command].nil?
52:         migration_command params[:migration_command]
53:         symlink_before_migrate({})
54:         action deploy_config[:action]
55: 
56:         scm_provider :git
57:         enable_submodules deploy_config[:enable_submodules]
58:         shallow_clone deploy_config[:shallow_clone]
59: 
60:         before_migrate do
61:           link_tempfiles_to_current_release
62: 
63:           # copy shared/config => release/config
64:           if File.directory? "#{deploy_config[:deploy_to]}/shared/config"
65:             directory "#{release_path}/config"
66:             execute "cp #{deploy_config[:deploy_to]}/shared/config/* #{release_path}/config"
67:           end
68: 
69:           directory "#{release_path}/temp" do
70:             mode 0777
71:           end
72: 
73:           Billy.install(release_path, node[:environment])
74:         end
75:       end
```

**Comment by pattonjp** [comment]
running into the same issue... 

this was no help: 
deploy_revision "appname" do
  environment {}

this fixed our issue: 
deploy_revision "appname" do
  environment Hash.new

best of luck

**Comment by ujuettner** [comment]
Thanks @pattonjp for stepping in. You're right - I missed that you have to supply a Hash object. So, either

```
environment Hash.new
```

or

```
environment({})
```

should work.

**Comment by noazark** [comment]
@pattonjp, if we ever bump into each other, I owe you a coffee (at least). Thanks!

To clarify,

```
envrionment {} # this is a block, just like do...end
environment({}) # this is a Hash passed in as an argument
```

**Comment by pschrammel** [comment]
Hi, 
ran into the same issue but am too new to chef to know where do I have to put this code (I guest this will be somewhere in a custom recipe) and at which AWS stage I have to run it. THX

**Comment by workeitel** [comment]
This issue was fixed by https://github.com/aws/opsworks-cookbooks/commit/c6339fafabdb4f627f2f3fdada2f41dfc45349e2 released with version 331 on 1th december

**Comment by pschrammel** [comment]
I tried to install a server yesterday but failed. I don't think the commit you mention fixes the problem.

**Comment by pschrammel** [comment]
sorry wrong issue...
