### ISSUE TITLE
Chef debug logs are not available

### ISSUE THREAD

**Issue by benlangfeld** [aws/opsworks-cookbooks#261]
According to the documentation, OpsWorks should run Chef in debug mode: http://docs.aws.amazon.com/opsworks/latest/userguide/troubleshoot-debug-log.html

My OpsWorks logs show only INFO, and not DEBUG. I cannot find any way to get Chef DEBUG logs.

**Comment by nisevi** [comment]
Hi, I'm almost new in this, but I think that if you have a Vagrantfile you can try what you are doing locally, you can add "chef.log_level = :debug" and I think that you are gonna be able to see the DEBUG info.

**Comment by benlangfeld** [comment]
Thanks @nisevi, but I don't want debug logs from a local run, I want logs from a run in the real environment.

**Comment by fh** [comment]
@benlangfeld I ran into the same issues recently, and according to AWS support, this behaviour has been changed with Chef 11.10 - there is no useful way to access Chef::Log.debug any more.

**Comment by dawalama** [comment]
@benlangfeld @fh I am also having the same issue. 

/opt/aws/opsworks/current/config/bootstrap.yml has verbose set to true, and still the log level is set to INFO.

Even after manually setting the chef_log_level to debug in /opt/aws/opsworks/current/lib/instance_agent/chef/runner.rb I am still not seeing DEBUG log. 

If you guys figure it out, I would be interested to know.

**Comment by fh** [comment]
@dawalama I already did, see above: There is just no useful way of doing so with Chef 11.10. Sorry :)

**Comment by dawalama** [comment]
@benlangfeld @fh

I was able to get some basic DEBUG to show up by doing the following in my recipe 

``` some-recipe.rb
require 'chef/log'
Chef::Log.level = :debug
.....
```

Also figured out that you can set the following as custom_json in your stack setting to enable debug.

```
{"opsworks":{"chef_log_level":"debug"}} 
```

But it is still not showing the stdout from bash scripts. So the above debug is almost useless for my purpose.

**Comment by aeberlin** [comment]
``` ruby
require 'mixlib/shellout'

def do_debug(cmd, workdir = '/home/foo', ignore_failures = false)
  cmd << "; #{ignore_failures}" if ignore_failures
  shell_instance = Mixlib::ShellOut.new("cd #{workdir} && #{cmd}")

  Chef::Log.info "DEBUG:  #{cmd}"
  Chef::Log.info "RESULT: #{shell_instance.tap(&:run_command).stdout}"
end
```
