### ISSUE TITLE
Node.js apps must listen on port 80 in order to pass health checks

### ISSUE THREAD

**Issue by monsieurBelbo** [aws/opsworks-cookbooks#265]
I'm running a node worker, that get's restarted every 1 minute because the application is not listening on port 80, thus failing the health check (which attempt to perform a GET and receive a 200).

My app is a worker, and does not need to listen on any port or serve HTTP for that matter, and it seems a bit too much running a web server just to respond to a health check.

Is there a way to provide another type of health check for my app? Or maybe some settings I can change through a custom JSON?

**Comment by Pitta** [comment]
If its a worker do you even need an ELB and health check? You do not need a load balancer at all if the worker is a consumer. I'm doing this with an AutoScaling group with no ELB. The AutoscalingGroup has its own health check based on the EC2 instance health.

**Comment by monsieurBelbo** [comment]
I agree, I don't need a load balancer at all. But I'm trying to figure out how to do this using the node.js cookbook.

**Comment by gcochard** [comment]
Sounds like this is Monit restarting your worker, rather than the ELB doing so. That said, node's built-in http server would be very low impact to add to your app: 

``` js
// bind to port 80
require('http').createServer(function(req,res){res.writeHead(200);res.end();}).listen(80);
// ...then drop permissions
process.setgid('nobody');
process.setuid('nobody');
```

I haven't looked at how to remove Monit from the opsworks application stack.

**Comment by gcochard** [comment]
See #186
