### ISSUE TITLE
Ruby 2.2

### ISSUE THREAD

**Issue by k0nserv** [aws/opsworks-cookbooks#266]
How is work progressing for supporting Ruby 2.2 in Ruby and Ruby On Rails apps?

**Comment by arsduo** [comment]
+1

**Comment by nicholasjon** [comment]
+1

**Comment by seanabrahams** [comment]
+1

**Comment by zrisher** [comment]
+1

**Comment by jeveloper** [comment]
+1  With Phusion Passenger, it'll run GC a lot more efficient and you won't have to  
 use PhusionPassenger::Rack::OutOfBandGc

**Comment by ainame** [comment]
+1

**Comment by gkaemmer** [comment]
+1

**Comment by morgoth** [comment]
I know that pinging won't speed it up, but is there any estimation when this is ready?

**Comment by jweiss** [comment]
We have this on our radar of course and will hopefully have an update soon.

**Comment by kyledecot** [comment]
+1

**Comment by ainame** [comment]
Today, I found this patch of ruby cookbooks which have deployed by opsworks, I will try to use ruby 2.2.

```
> diff -r /opt/aws/opsworks/releases/20150130111435_33500020150130111435/cookbooks/ruby/attributes/ruby.rb /opt/aws/opsworks/releases/20150210181912_33600020150210181912/cookbooks/ruby/attributes/ruby.rb
20a21,29
> when "2.2"
>   default[:ruby][:major_version] = '2'
>   default[:ruby][:minor_version] = '2'
>   default[:ruby][:patch_version] = '0'
>   default[:ruby][:pkgrelease]    = '1'
>
>   default[:ruby][:full_version] = [node[:ruby][:major_version], node[:ruby][:minor_version]].join(".")
>   default[:ruby][:version] = [node[:ruby][:full_version], node[:ruby][:patch_version]].join(".")
```

**Comment by k0nserv** [comment]
Indeed here's the commit https://github.com/aws/opsworks-cookbooks/commit/f654891dd079850f9089aea3a71a71db3823b73b#diff-bb2e48e6c13b4cb9abed60f8ed18b29fR21

Seems to only be in master-11.10 so far

**Comment by ainame** [comment]
I've succeed to install ruby 2.2 with `execute recipe` command in Custom Layer.

```
[root@ainame-dev chef]# ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

Maybe, OpsWorks have already deployed latest cookbooks to our environments,
but, it haven't modified management console of Rails Layer.

I don't know the release cycle of OpsWorks's cookbooks, however it have been deployed already.
That's a little bit scary.

**Comment by tachiba** [comment]
Thanks to @ainame , I've also succeed to install 2.2 by setting below to custom JSON.
(But, I afraid to break something...)

``` json
{
  "opsworks": {
    "ruby_version": "2.2"
  },
  "opsworks_rubygems": {
    "version": "2.4.6"
  }
}
```

**Comment by jweiss** [comment]
We will rollout support for Ruby 2.2 in the UI and API next week. The cookbooks and agent already support it. So you can use it today by setting the custom JSON. We recommend removing the custom JSON and using the explicit settings once they are available. I’m sorry for any confusion this caused.

**Comment by ainame** [comment]
@jweiss By the way, what is the best method to use ruby 2.2 in Custom Layer?
Recently, I'm using some Custom Layer instead of Rails Layer, because I want to purge frontend Rails app server from backend Rails app server (e.g. sidekiq workers).

So, I put `normal["opsworks"]["ruby_version"] = "2.1"` in `MY_CUSTOM_COOKBOOKS/ruby/attributes/customize.rb`

**Comment by jweiss** [comment]
Three different options:

a) Create a Rails layer and set the options there
b) Set the Ruby settings using custom JSON
c) Set the Ruby settings using an attribute file

**Comment by ainame** [comment]
@jweiss Ah, just as I thought I was. Thank you for responding me :smile_cat:

**Comment by jweiss** [comment]
Ruby 2.2 is now officially available in the UI too

**Comment by k0nserv** [comment]
Awesome. I am closing the issue now.
