### ISSUE TITLE
Rename unicorn to opsworks_unicorn

### ISSUE THREAD

**Issue by sheldonh** [aws/opsworks-cookbooks#268]
The opsworks cookbook prevents custom bookshelves from using the community unicorn cookboo:

```
[2015-01-15T22:28:46+00:00] INFO: HTTP Request Returned 412 Precondition Failed: Could not satisfy version constraints for: unicorn
```

I can't think of a way to deal with this other than renaming opsworks' unicorn recipe to opsworks_unicorn.

**Comment by dieend** [comment]
All opsworks cookbook need to be renamed.

https://github.com/aws/opsworks-cookbooks/issues/217

**Comment by githuesch** [comment]
As stated in #217, please check out [our launch announcement](https://forums.aws.amazon.com/ann.jspa?annID=3397) for Chef 12 Linux. Built-in cookbooks like `unicorn` that previously caused clashes with community cookbooks are not namespaced, but completely removed. The announcement links to our documentation for getting started with this clean, new approach.
