### ISSUE TITLE
Please allow more than 20 environmental variables

### ISSUE THREAD

**Issue by evdevdev** [aws/opsworks-cookbooks#274]
Hi OpsWorks,

I have fairly quickly hit the upper limit of environmental variables. Why is this capped at 20? Is there any possibility of this going beyond 20? 

Here are the variables I have: 

Twilio - requires 2 values
Stripe - requires 2 values
Carrierwave - requires 2 values
Mandrill - requires 4 values
Mailgun - requires 3 values (why do we have two mail clients? because we balance between them in outages)
Airbrake - 1 value
Mixpanel - 1 value
Pusher - 3 values
Quickbooks Online - 2 values

And already - that's 20 positions filled up. And in the future we might add further integrations. 

Please advise.

**Comment by jweiss** [comment]
You can always add the values directly in the custom JSON or in a Chef recipe as a workaround.

I will have a look at raising the limit on the backend but it will require some time.

**Comment by githuesch** [comment]
I just added 200 variables to an app. We had a limit on the number of variables the day we launched support for environment variables, but quickly switched to a byte size limit of 10240 bytes instead.
What exactly limits you to use only 20 variables?

**Comment by evdevdev** [comment]
I am going off of this: http://docs.aws.amazon.com/opsworks/latest/userguide/workingapps-creating.html#workingapps-creating-environment

It says: 

> You can specify up to twenty environment variables for each app, which are specific to the app. For example, if you have two apps, the environment variables that you define for the first app are not available to the second app and vice versa. You can also define the same environment variable for multiple apps and assign it a different value for each app.

Is this possibly just out of date?

**Comment by githuesch** [comment]
That's out of date indeed. I'll have the doc team update it. Thanks for pointing this out.

**Comment by fredrik** [comment]
Looks like the docs are updated. Good to close this one, @githuesch. :+1:
