### ISSUE TITLE
Feature Request: Multi-instance after deploy hook

### ISSUE THREAD

**Issue by gkaemmer** [aws/opsworks-cookbooks#282]
It'd be very useful for monitoring purposes if there was a way to run code when an OpsWorks deployment completes, as shown by a green check mark in the "Deployments" console. To my knowledge, doing this with a recipe is impossible, as there is no way of detecting whether the deploy was successful on all instances.

**Comment by githuesch** [comment]
I agree that it's impossible in a recipe, so it doesn't really belong into an issue in our cookbook repo.

**Comment by fredrik** [comment]
@gkaemmer, do you have a non-recipe solution to this problem?

**Comment by gkaemmer** [comment]
@fredrikmollerstrand nope, as far as I'm aware there's no way to do this. I think it would require a webhook feature or something in the Opsworks console.
