### ISSUE TITLE
Opsworks + Rails + Any Gem that pulls in ExecJS !work with opsworks_nodejs

### ISSUE THREAD

**Issue by markalanevans** [aws/opsworks-cookbooks#284]
Hey guys,

Just wondering if this was a known issue.

Using the most basic config seen below, if you also use any GEM that includes ExecJS for ex:

Because node is installed "/usr/local/bin/node"  i believe its not in the path for the apache users and And any user will get errors like:
#### Bundle File

```
gem 'uglifier'
gem 'coffee-rails'
```
##### Error Message

```
Message from application: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
```
#### Hack

This will fix it but of course its not out of the box...

```
ln -s /usr/local/bin/node /usr/bin/node
```
#### App & Layer

App Type: "Ruby on Rails"
Amazon Linux 2014.09
Chef 11.10
Custom Recipe: "opsworks_nodejs"
Custom JSON

```
{
  "opsworks_nodejs": {
    "version": "0.10.33"
  }
}
```

Am I doing something wrong?

**Comment by markalanevans** [comment]
I did come across this possible other solution:

_config/boot.rb_

```
ENV["PATH"] = "/usr/bin:#{ENV['PATH']}"
ENV["EXECJS_RUNTIME"] = 'Node'
```

Although I haven't tested it yet.

**Comment by aaronlerch** [comment]
I have been hunting this same issue over the past few days. What I'm seeing is with our rails app, on OpsWorks, using the unicorn server. Unicorn starts correctly (including ExecJS loading correctly and finding `node` in `/usr/local/bin`) but when we deploy an update, suddenly the new unicorn master process fails with the ExecJS `ExecJS::RuntimeUnavailable` exception.

I've been digging into it and from what I can tell, when unicorn starts (or you restart it with `unicorn restart`) it succeeds, but every subsequent deploy (when it does "Gem refresh") the `/usr/local/bin` directory is missing `node` and `npm`, according to the code running in the ExecJS gem in the unicorn process.

I still haven't found the solution, but I'm still digging.
This is on Ubuntu 14.04, also.

**Comment by aaronlerch** [comment]
Found our issue. Not the solution, per se, but at least the root cause. It's a timing issue. When we deployed, the opsworks node recipes were removing `/usr/local/bin/node` and `/usr/local/bin/npm` and re-installing them, but that short window was just enough time for ExecJS to try and look for them and not find them. Insanity.

Our solution, since we don't need the most recent version and Ubuntu 14.04 ships with a "good enough" nodejs version, was to just install the packages directly and bypass the opsworks recipes.

This is the kind of thing we saw in the chef logs:

```
[2015-03-11T18:00:00+00:00] INFO: Processing package[Remove outdated package opsworks-nodejs] action remove (opsworks_nodejs::default line 19)
[2015-03-11T18:00:02+00:00] INFO: package[Remove outdated package opsworks-nodejs] removed
[2015-03-11T18:00:02+00:00] INFO: Processing log[downloading] action nothing (opsworks_nodejs::default line 25)
[2015-03-11T18:00:02+00:00] INFO: Processing opsworks_commons_assets_installer[Install user space OpsWorks NodeJS package] action install (opsworks_nodejs::default line 32)
[ Wed, 11 Mar 2015 18:00:02 +0000 ] downloader: Successfully created temporary download directory. (/var/lib/aws/opsworks/cache.stage2/opsworks_assets/opsworks-nodejs.iLpUXKzq)
2015-03-11 18:00:02 URL:https://opsworks-instance-assets-us-east-1.s3.amazonaws.com/packages/ubuntu/14.04/opsworks-nodejs_0.10.29-1_amd64.deb [5633840/5633840] -> "/var/lib/aws/opsworks/cache.stage2/opsworks_assets/opsworks-nodejs.iLpUXKzq/opsworks-nodejs_0.10.29-1_amd64.deb" [1]
[ Wed, 11 Mar 2015 18:00:02 +0000 ] downloader: File size test passed.
[ Wed, 11 Mar 2015 18:00:02 +0000 ] downloader: Checksum proof skipped.
[ Wed, 11 Mar 2015 18:00:02 +0000 ] downloader: Successfully downloaded https://opsworks-instance-assets-us-east-1.s3.amazonaws.com/packages/ubuntu/14.04/opsworks-nodejs_0.10.29-1_amd64.deb
[2015-03-11T18:00:02+00:00] INFO: Processing package[opsworks-nodejs] action install (/var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_commons/providers/assets_installer.rb line 6)
rm -rf /var/lib/aws/opsworks/cache.stage2/opsworks_assets/opsworks-nodejs.iLpUXKzq
```

Crazy that those few seconds were enough for ExecJS to look for node while it was missing.
