### ISSUE TITLE
Node.js layer deployment fails after cookbooks update on Feb 06

### ISSUE THREAD

**Issue by Grety** [aws/opsworks-cookbooks#287]
after automatic execute of updated recipes (execute_recipes) node.js deployment fails in cookbooks with error 

```
[2015-02-10T02:52:58+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/build-essential into a Chef object: Option default must be a kind of [String, Array, Hash]!  You passed false.
[2015-02-10T02:52:58+00:00] ERROR: #<NoMethodError: undefined method `to_hash' for nil:NilClass>
```

**Comment by awsrequena** [comment]
The description of the failure is very vague. Could you provide more context.
1. Obviously you're using custom cookbooks
2. Please provide a more extensive trace of the error.  A reference to a line of code, where the error happens will be very helpful

**Comment by Grety** [comment]
Our overall team's expertise in Berskhelf and Chef is so poor that  we would never think of using custom cookbooks. It 's a default setup of AWS t1-micro node.js server. 
Having total 19 default cookbooks: 
see [screenshot](http://postimg.org/image/p9exwjcll/)
This is the log file of [OpsWorks execute_recipes](https://s3.amazonaws.com/radical-media/73408623-38ed-4269-8a2e-47f456fe23bc.txt)
This is the log file of [Node application deployment](https://s3.amazonaws.com/radical-media/d616c9a4-328d-4e77-8df8-59a7a5001273.txt)
Which show actually same error, and it is inside cookbooks provided by Amazon
