### ISSUE TITLE
Tons of timeouts after recent update

### ISSUE THREAD

**Issue by albertsj1** [aws/opsworks-cookbooks#289]
After the recent update to clear the berkshelf cache, I'm experiencing timeouts on 75% of my instances in opsworks.
The guilty line of code is here: https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/opsworks_berkshelf/providers/runner.rb#L17

I can get around this by using an override as suggested [here](http://stackoverflow.com/a/28590629/1298678); however, it would be nice if the timeout value could be exposed as an attribute.

**Comment by githuesch** [comment]
That's a bit surprising. Please have a look at https://github.com/berkshelf/berkshelf/commit/aba2e7dc0909261e7f5a9cd6f39f515de857e2b9. The latest version of Berkshelf doesn't leave those directories behind any more. In older versions they shouldn't be used for more than a single run. The reason we added the code to remove those was that they were using up disk space, which can lead to severe problems.

We are currently looking into bumping the default timeout for shellout.
Out of curiosity, the link you provided sets the timeout to 900 seconds, did you use that and did it work for you?

**Comment by albertsj1** [comment]
We're using berkshelf 2.0.18 still for 'reasons'.  We're using all git
sources for our cookbooks which are downloaded from our mirror and it
already takes quite a while sometimes to download the cookbooks.  I guess
clearing the cache was the last straw causing it to hit the timeout.

Yes, bumping the timeout to 900s fixed our timeout issue for all of our
machines.

**Comment by githuesch** [comment]
Got it. We're looking into setting the timeout high enough.
Making this configurable turned out to be harder than expected.
