### ISSUE TITLE
Update to Ruby 2.2.1

### ISSUE THREAD

**Issue by rollbrettler** [aws/opsworks-cookbooks#294]
Is there a way to update ruby to the latest patch version? I already tried to use a custom json with `"ruby":{"patch_version":"1"}` but the package wasn’t available.

**Comment by ainame** [comment]
I want to use ruby v2.2.1 for fixing this issue.

https://bugs.ruby-lang.org/issues/10686

**Comment by k0nserv** [comment]
ping @jweiss

**Comment by k0nserv** [comment]
I've created a PR for this https://github.com/aws/opsworks-cookbooks/pull/296

**Comment by k0nserv** [comment]
Okay Jonathan responded to the PR, they need to build binaries for 2.2.2 so my PR was a bit to optimistic :) I asked Jonathan for a timeline on this progress

**Comment by jagthedrummer** [comment]
Would love to be able to use 2.2.2. Any word on this?

**Comment by dlackty** [comment]
After latest agent update few days ago, Ruby 2.2.2 is already available on OpsWorks.

**Comment by jagthedrummer** [comment]
Nice! Thanks for the update.
