### ISSUE TITLE
deploy_to turning into /dev/xvda1

### ISSUE THREAD

**Issue by vanch** [aws/opsworks-cookbooks#301]
Hi.

Looks like you have a bug here https://github.com/aws/opsworks-cookbooks/commit/ff196d509e30d9147add3994b2f845242ac687a4

Seems like author misplaced keys and values on 55th line, I can't say accurately.

For us, the issue looks like:

We're trying to run clear instance and deployment failing on trying to create /dev/xvda1/webapp. So it seems like bug.

Thanks.

**Comment by jarv** [comment]
Thanks for the report, looking into this now. What type of instance are you using and what are the exact steps to reproduce the issue?

**Comment by jarv** [comment]
@vanch Can you also provide your stack ID?

**Comment by Aegis8** [comment]
Hi,

Here is the info: Instance is t2.small and stack ID: e49474a0-95d7-4faf-bf44-6edf3837c45c

We run a webapp deploy script that should create a directory /srv/www/webapp. (recipe uses deploy_to)

I'm currently running the build again.

**Comment by jarv** [comment]
I've been able to reproduce the error using your OS / Instance combination.
It's not ideal and only temporary but if you login to your instance and edit
`/opt/aws/opsworks/current/cookbooks/deploy/attributes/deploy.rb`
and replace:

```
 app_mount = node[:filesystem].select {|k,v| v["mount"] == "/srv/www"}.keys[0]
 default[:deploy][application][:deploy_to] = app_mount ? "#{app_mount}/#{application}" : "/srv/www/#{application}"
```

with:

```
default[:deploy][application][:deploy_to] = "/srv/www/#{application}"
```

you should be able to re-deploy without error

**Comment by vanch** [comment]
We already solved it temporarely setting JSON per app variable ":deploy_to" to "/srv/www".
Hope you'll fix it ASAP. Thanks.

Update: oops, looks like it didn't fix it.

**Comment by Aegis8** [comment]
Thanks for the assistance, I applied your fix, as well, and the deploy was successful.

**Comment by jarv** [comment]
That breaking change has been reverted until we come up with a better solution
https://github.com/aws/opsworks-cookbooks/commit/d266b6fbd0f77b5e3e150951b0b8aa83bb0c98cb
