### ISSUE TITLE
Update dependencies cookbook metadata to use correct types

### ISSUE THREAD

**Issue by jpslav** [aws/opsworks-cookbooks#31]
Looks like the `metadata.rb` file in the `dependencies` cookbook is using 'boolean' types which are not allowed.  http://wiki.opscode.com/display/chef/Metadata#Metadata-attribute says that only types of 'string' and 'array' are allowed.

I'm pulling these cookbooks into a berkshelf on Vagrant to test my cookbooks out before deploying to AWS.  These bad types are giving me errors when berkshelf (or its buddies) try to validate the metadata.

Notes:
- #6 might take care of this altogether?
- _Very_ related pull request at scalarium: https://github.com/scalarium/cookbooks/pull/15
- Similar situation: https://github.com/fnichol/chef-rvm/issues/20

**Comment by jbraeuer** [comment]
Closing the issue as problem has been fixed.

**Comment by jpslav** [comment]
Howdy -- Can you fix this in the `release-chef-0.9` branch too?  The `type` there is still `boolean`, which is not allowed per that opscode link above.
