### ISSUE TITLE
rhel Helper Method Breaks Chef Convergence

### ISSUE THREAD

**Issue by jcderose** [aws/opsworks-cookbooks#321]
I'm testing a custom cookbook that requires the OpsWorks built-in apache2 cookbook. However, I'm getting this error message upon convergence:

```
       Compiling Cookbooks...
   ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/apache2/attributes/apache.rb
       ================================================================================

       NoMethodError
       -------------
       Undefined method or attribute `rhel7?' on `node'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/apache2/attributes/apache.rb:45:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/apache2/attributes/apache.rb:

        38:    default[:apache][:dir]           = '/etc/httpd'
        39:    default[:apache][:log_dir]       = '/var/log/httpd'
        40:    default[:apache][:user]          = 'apache'
        41:    default[:apache][:group]         = 'apache'
        42:    default[:apache][:binary]        = '/usr/sbin/httpd'
        43:    default[:apache][:icondir]       = '/var/www/icons/'
        44:    default[:apache][:init_script]   = "service httpd"
        45>>   if rhel7?
        46:      default[:apache][:version]       = "2.4"
        47:    else
        48:      default[:apache][:version]       = "2.2"
        49:    end
        50:    default[:apache][:conf_available_dir]  = "#{node[:apache][:dir]}/conf.d"
        51:    default[:apache][:conf_enabled_dir]    = "#{node[:apache][:dir]}/conf.d"
        52:    default[:apache][:pid_file]      = '/var/run/httpd/httpd.pid'
        53:    default[:apache][:lock_dir]      = '/var/run/httpd'
        54:    default[:apache][:lib_dir]       = node[:kernel][:machine] =~ /^i[36']86$/ ? '/usr/lib/httpd' : '/usr/lib64/httpd'

       [2015-07-20T16:59:01+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-20T16:59:01+00:00] ERROR: Exception handlers complete
       [2015-07-20T16:59:01+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 58.392628087 seconds
       [2015-07-20T16:59:01+00:00] ERROR: Undefined method or attribute `rhel7?' on `node'
       [2015-07-20T16:59:01+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I noticed this started after the rhel helper method was added to the apache2 cookbook.

https://github.com/aws/opsworks-cookbooks/commit/6bbb75ee37781fa955579be0b2519d2a7f836b81

**Comment by jarv** [comment]
@jcderose the helper function is defined in opsworks_commons/libraries/predicates.rb, and unfortunately right now opsworks doesn't support testing cookbooks with kitchen without the entire repo checked out on disk. (see this blog post https://sethvargo.com/using-amazon-opsworks-with-berkshelf/ for possible workarounds)

Since this was something that was working before the commit can you give the exact configuration/steps to reproduce the issue?

**Comment by jcderose** [comment]
Hi @jarv, I'm actually currently using test kitchen with the entire OpsWorks repo checked out on disk, and I'm still getting the error mentioned above. Here are my steps:
- In my .kitchen.yml file, I specify my custom cookbook and necessary OpsWorks attributes:

```
suites:
  - name: default
    run_list:
      - recipe[setup-ebs-encryption]
    attributes:
      {
        "opsworks": {
            "stack": {
                "name": "DevOps-POA"
              },
              "instance": {
                "infrastructure_class": 'ec2',
                "availability_zone": 'us-west-2a'
             }
        }
      }
```
- In the custom cookbook's default recipe, I specify the dependency on the built-in mod_php5_apache2 recipe (which in turn depends on the built-in apache2 recipe):

```
#
# Cookbook Name:: setup-ebs-encryption
# Recipe:: default
#
# Copyright 2014, Consensus Corporation
#
# All rights reserved - Do Not Redistribute
#

include_recipe "mod_php5_apache2"

# additional recipe code
```
- In the custom cookbook's metadata.rb file, I also specify the dependency:

```
name             'setup-ebs-encryption'
maintainer       'Consensus Corporation'
maintainer_email 'consensus-it@consensuscorp.com'
license          'All rights reserved'
description      'Installs/Configures setup-ebs-encryption'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'mod_php5_apache2'
```
- In my Berksfile, I specify the entire OpsWorks repo of built-in cookbooks:

https://gist.github.com/jcderose/1f054f7714571c25d7b1#file-gistfile1-txt
- I run `kitchen create` to create the EC2 instance via test kitchen.
- I run `kitchen converge` to install Chef and test the recipe in question, and get the error output above.

**Comment by jarv** [comment]
@jcderose I was able to successfully run `kitchen converge` on an ec2 instance with the latest cookbooks using "option #2" in this blog post - https://sethvargo.com/using-amazon-opsworks-with-berkshelf/ . Can you try using that method instead?  

After checking out the opsworks-cookbooks repo locally here is the Berksfile I used:

```
def opsworks_cookbook(name, version = '>= 0.0.0', options = {})
    cookbook name, version, { path: "opsworks-cookbooks/#{name}" }.merge(options)
end

source "https://supermarket.chef.io"

opsworks_cookbook 'opsworks_initial_setup'
opsworks_cookbook 'ssh_host_keys'
opsworks_cookbook 'ssh_users'
opsworks_cookbook 'mysql'
... (rest of cookbooks)
cookbook 'test', path: 'cookbooks/test'
```

test/metadata.rb

```
name        "test"
description "test cookbook"
version     "1.0.0"
depends     "mod_php5_apache2"
```

test/recipes/default.rb

```
include_recipe "mod_php5_apache2"
package "git"
```

**Comment by jcderose** [comment]
@jarv I ran `berks install` before `kitchen create`/`kitchen converge` and that resolved the issue. I couldn't tell you why it resolved the issue though, since I had already run `berks install` when I first ran into this problem.
