### ISSUE TITLE
OpsWorks Agent 3429+ trying to use systemd on Ubuntu 14

### ISSUE THREAD

**Issue by mattlqx** [aws/opsworks-cookbooks#352]
Agent updates are failing on my Ubuntu 14.04/10 AMIs because they're trying to start the service via systemd, but these versions of Ubuntu use Upstart for init services. The last agent I'm able to successfully use is 3428.

Here's the /var/log/aws/opsworks/updater.log output from an update attempt. https://gist.github.com/mattlqx/6293024a4989dcd9c322

If I touch /etc/systemd/system/opsworks-agent.service to fix the above error, I get https://gist.github.com/mattlqx/1c0e5812036caf64cb7f, which fails on it trying to use systemctl.

Apologies if this is not the appropriate avenue for reporting issues with agent.

**Comment by wbingli** [comment]
Looks you have systemd installed in your ubuntu. Is it ubuntu 14.04 or ubuntu 14.10? How about retry agent update after uninstall systemd?

**Comment by mattlqx** [comment]
14.10 specifically. Definitely some sort of change in the agent after 3428 though. systemd package has apparently always been on it, not sure if it came on the AMI I based it on or if something else installed it, doesn't show up as being installing in any of my logs though.

Anyway, removing the systemd package and upgrading worked, thanks!
