### ISSUE TITLE
Node.js 4 LTS and 5 support

### ISSUE THREAD

**Issue by jonricaurte** [aws/opsworks-cookbooks#353]
Hi,

Was wondering if anyone was able to look into at least getting Node.js version 4 supported and maybe start on version 5.

Thanks.

**Comment by holyshared** [comment]
+1

**Comment by jonricaurte** [comment]
Closing this due to:

https://blogs.aws.amazon.com/application-management/post/Tx1T5HNA1TSU8NH/AWS-OpsWorks-Now-Supports-Chef-12-for-Linux

"Chef 11.10 and earlier versions for Linux will continue to support built-in layers. The built-in cookbooks will continue to be available at https://github.com/aws/opsworks-cookbooks/tree/release-chef-11.10.

Beginning in January 2016, you will no longer be able to create Chef 11.4 stacks using the OpsWorks console. Existing Chef 11.4 stacks will continue to operate normally, and you will continue to be able to create stacks with Chef 11.4 by using the API."

http://docs.aws.amazon.com/opsworks/latest/userguide/chef-12-linux.html
