### ISSUE TITLE
how to remove 127.0.1.1 loopback from hsost?

### ISSUE THREAD

**Issue by hamsterksu** [aws/opsworks-cookbooks#375]
Hi 

i know that **aws_opsworks_system** generates hosts from template.
i would like to remove 127.0.1.1 from hosts. how to do it?

i have found article about overriding  - 
http://docs.aws.amazon.com/opsworks/latest/userguide/cookbooks-101-opsworks-templates.html 

but i haven't got success result.

my repo is available on github - 
https://github.com/dataart-telco/restcomm-opsworks

Could you help me with this?

**Comment by CaseyBurnsSv** [comment]
hi @hamsterksu -- how did you resolve this?

**Comment by hamsterksu** [comment]
@CaseyBurnsSv sorry for delay,
you have 2 options:
1. replace line in file - https://github.com/dataart-telco/restcomm-opsworks/blob/e37df3f48a976b38f1fdd152df5d5046580fb277/restcomm/recipes/hosts.rb 
2. or use custom playbook to generate hosts - https://github.com/dataart-telco/restcomm-opsworks/tree/e37df3f48a976b38f1fdd152df5d5046580fb277/hosts 
   to include it to yours https://github.com/dataart-telco/restcomm-opsworks/blob/e37df3f48a976b38f1fdd152df5d5046580fb277/restcomm/metadata.rb#L13 
   how to use - https://github.com/dataart-telco/restcomm-opsworks/blob/e37df3f48a976b38f1fdd152df5d5046580fb277/restcomm/recipes/loadbalancer_run.rb#L6
