### ISSUE TITLE
Node.js 4.x or 5.x support?

### ISSUE THREAD

**Issue by danielsantiago** [aws/opsworks-cookbooks#377]
Do you have any time frame on when you will support node version 4.x or 5.x?

**Comment by shrinathaithal** [comment]
+1

I am looking for the same. We had to write a custom cookbook to get this
working with custom layer for now.

**Comment by mmarod** [comment]
Excuse my ignorance but is there a list of supported versions of node anywhere? As far as I can tell it is impossible to get a directory listing of the bucket containing the opsworks_nodejs debs so its a guessing game. I am also looking to get node 5 working with this cookbook and it seems like it is just waiting on an up to date deb.

**Comment by githuesch** [comment]
The list you're looking for is in our documentation. In fact, there are multiple lists for the different supported OS options. http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-os-linux.html.

That said, we do not have a time frame for Node.js 4.x or 5.x, but as you can see in https://github.com/aws/opsworks-cookbooks/issues/358#issuecomment-202287879, we're probably going to add that eventually.

**Comment by mmarod** [comment]
Thanks -- That's exactly what I was looking for

**Comment by paparga** [comment]
Hi @shrinathaithal,

can you share your custom cookbook?

Thanks!

**Comment by shrinathaithal** [comment]
Forget custom, I started using community cookbook. Here are the steps if you are still interested - 
1. Use this in your Berksfile - 
   `cookbook 'nodejs', git:'https://github.com/redguide/nodejs.git', tag: 'v2.4.0'`
2. In layers > setup add this - `nodejs::npm_from_source` & `nodejs::npm_packages`
3. This goes in stack settings JSON - 
   `
   "nodejs": {
   "install_method": "source",
   "version": "5.7.1",
   "npm_packages": [
     {
       "name": "pm2",
       "options": [ "-g" ]
     }
   ]
   }
   `

Let me know if that helped.

**Comment by codemonkey84** [comment]
@shrinathaithal  I however get this error:

## NoMethodError

No resource or method named `ark' for`Chef::Recipe "npm_from_source"'

## Cookbook Trace:

/var/lib/aws/opsworks/cache.stage2/cookbooks/nodejs/recipes/npm_from_source.rb:29:in `from_file'

**Comment by jweiss** [comment]
Yes, please use the Chef community cookbook for Nodejs on Chef 12 for OpsWorks.
