### ISSUE TITLE
Please provide a git repo for the opsworks agent installer

### ISSUE THREAD

**Issue by andrewfenn** [aws/opsworks-cookbooks#388]
I know this isn't the right place to be asking for this exactly, but I've tried asking everywhere else, including on the forums, via priority support, each time I get told that this information is being fed back to the team without any response back for a couple of years now.

Can you guys please provide a git repo of the opsworks agent installer.. even if it's just parts of it, that would be useful for submitting patches against as I'm so tired of having to submit patches via support requests.

Having one place where I can submit pull requests to you guys would be a much better way forward and I can't understand why (unless I'm not looking in the right place?) there isn't one available.

Thanks,
Andrew

**Comment by jweiss** [comment]
Hi Andrew,

Thank you for this feedback, we are discussing this internally and with legal and will follow up.

Best,
Jonathan
