### ISSUE TITLE
nodejs provisioning has a number of false assumptions...

### ISSUE THREAD

**Issue by ajohnstone** [aws/opsworks-cookbooks#39]
Chef recipe

```
Setup: opsworks_initial_setup, opsworks_nodejs, opsworks_nodejs::npm, ssh_users
Configure: ssh_users, agent_version, opsworks_nodejs::configure
Deploy: deploy:nodejs, photobox-checkout::default
Undeploy: deploy::nodejs-undeploy
Shutdown: opsworks_shutdown::default, deploy::nodejs-stop 
```

This installs apache bound to port 80, which at no point do I include apache.

```
root@nodejs-app3:/var/log/aws/opsworks# egrep -rin apache .
./installer.log:576:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: node nodejs-app3.localdomain loading cookbook passenger_apache2's attribute file /opt/aws/opsworks/releases/20130529164351_120/cookbooks/passenger_apache2/attributes/passenger.rb
./installer.log:603:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: node nodejs-app3.localdomain loading cookbook apache2's attribute file /opt/aws/opsworks/releases/20130529164351_120/cookbooks/apache2/attributes/apache.rb
./installer.log:629:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: Loading cookbook passenger_apache2's definitions from /opt/aws/opsworks/releases/20130529164351_120/cookbooks/passenger_apache2/definitions/passenger_web_app.rb
./installer.log:636:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: Loading cookbook apache2's definitions from /opt/aws/opsworks/releases/20130529164351_120/cookbooks/apache2/definitions/web_app.rb
./installer.log:637:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: Loading cookbook apache2's definitions from /opt/aws/opsworks/releases/20130529164351_120/cookbooks/apache2/definitions/apache_conf.rb
./installer.log:638:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: Loading cookbook apache2's definitions from /opt/aws/opsworks/releases/20130529164351_120/cookbooks/apache2/definitions/apache_site.rb
./installer.log:639:[Sat, 01 Jun 2013 18:18:30 +0000] DEBUG: Loading cookbook apache2's definitions from /opt/aws/opsworks/releases/20130529164351_120/cookbooks/apache2/definitions/apache_module.rb
```

monit is monitoring apache not the node services

```
check host node_web_app_checkout with address 127.0.0.1
  start program = "/bin/sh -c 'cd /srv/www/checkout/current; /usr/bin/env NODE_PATH=/srv/www/checkout/current/node_modules:/srv/www/checkout/current /usr/local/bin/node /srv/www/checkout/current/server.js'"
  stop program  = "/usr/bin/pkill -f 'node /srv/www/checkout/current/server.js'"
  if failed port 80 protocol HTTP
    request /
    with timeout 10 seconds
    then restart
check host node_web_app_services with address 127.0.0.1
  start program = "/bin/sh -c 'cd /srv/www/services/current; /usr/bin/env NODE_PATH=/srv/www/services/current/node_modules:/srv/www/services/current /usr/local/bin/node /srv/www/services/current/server.js'"
  stop program  = "/usr/bin/pkill -f 'node /srv/www/services/current/server.js'"
  if failed port 80 protocol HTTP
    request /
    with timeout 10 seconds
    then restart
```

```
  template "#{node[:monit][:conf_dir]}/node_web_app-#{application}.monitrc" do
    source 'node_web_app.monitrc.erb'
    cookbook 'opsworks_nodejs'
    owner 'root'
    group 'root'
    mode '0644'
    variables(
      :deploy => deploy,
      :application_name => application,
      :monitored_script => "#{deploy[:deploy_to]}/current/server.js"
    )
    notifies :restart, resources(:service => 'monit'), :immediately
  end
```

Additionally assumes the server invocation should be server.js

./opsworks_nodejs/templates/default/node_web_app.monitrc.erb

```
check host node_web_app_<%= @application_name %> with address 127.0.0.1
  start program = "/bin/sh -c 'cd <%= @deploy[:deploy_to] %>/current; /usr/bin/env NODE_PATH=<%= @deploy[:deploy_to] %>/current/node_modules:<%= @deploy[:deploy_to] %>/current /usr/local/bin/node <%= @monitored_script %>'"
  stop program  = "/usr/bin/pkill -f 'node <%= @monitored_script %>'"
  if failed port 80 protocol HTTP
    request /
    with timeout 10 seconds
    then restart
```

This is hard coded to port 80, it also assumes that monit will be the method in which to spawn the server.

Additionally the node_modules path may not be the same in current.

As an example I'm using an upstart script.

```
description "<%= @alias %>"

start on runlevel [2345]
stop on shutdown

respawn

script
   <% deploy_to = node[:nodejs][@alias][:deploy_to] %>
   cd <%= deploy_to %>/current/<%= @path %>/;
   exec sudo -u www-data sh -c "NODE_ENV=production NODE_PATH=<%= deploy_to %>/current/<%= @path %>/node_modules:<%= deploy_to %>/current/<%= @path %> node <%= deploy_to %>/current/<%= @script %>  >> <%= deploy_to %>/current/log/<%= @alias %>.log 2>&1"
end script
```

**Comment by ajohnstone** [comment]
This does not seem to resolve the above?

**Comment by awsrequena** [comment]
To clarify your assumptions:
- "This installs apache bound to port 80, which at no point do I include apache."
  No apache is not been installed, it merely load definitions and attributes from passenger_apache2 and apache2 as these are dependencies for other cookbooks.
- "monit is monitoring apache not the node services"
  Monit is monitoring PORT 80, which was supposed to be the default port used by the nodejs server. This was changed and is now read from @deploy[:nodejs][:port](Chef version > 11.4).  
- "Additionally assumes the server invocation should be server.js"
  Yes, we expect you to invoque the server via a script called "server.js" placed in the top level of your application. 
- "This is hard coded to port 80, it also assumes that monit will be the method in which to spawn the server."
  This is not the case any more for chef version > 11.4

I really don't see any issues in you comment.  I looks to me that you just need or expect things to be done differently and that you got some things wrong.  Or am I missing something?

**Comment by JamesMGreene** [comment]
> Yes, we expect you to invoque the server via a script called "server.js" placed in the top level of your application.

Why? I've never heard of any Node.js framework or convention that involves a file named "server.js". The defacto standard is "index.js", then perhaps "app.js"/"main.js" as a secondaries.

This should really just be configurable instead of forced upon consumers, otherwise we just have to add another step to our pre-commit or another recipe to our cookbooks to create/rename the file.

**Comment by githuesch** [comment]
The reason we expect a file named server.js is that this was also the name `npm start` expected. At least that was the case when we added support for Node.js. We didn't do a great job keeping the built-in Node.js layer up with trends in the community. I agree the start script should be configurable.

**Comment by JamesMGreene** [comment]
Ah, gotcha: https://docs.npmjs.com/misc/scripts#default-values

That's fair, I suppose. Having it configurable is definitely still preferable, though.

**Comment by ajohnstone** [comment]
This is a configurable value that is with package.json.
The default of server.js should not be assumed and should be a node value as you described.

Index is typically for modules not the entry point of an application.

**Comment by JamesMGreene** [comment]
> Index is typically for modules not the entry point of an application.

_*shrugs*_ I see no reason to _not_ use "index.js" (or, even better, whatever is in the `main` property of the "package.json" manifest (if present)) for an application vs. a module. That said, I also clearly have not been a frequent user of the `npm start` command either, so I was unfamiliar with the whole "server.js" alternative driver filename idea.

**Comment by jweiss** [comment]
closing as this is a very old issue
