### ISSUE TITLE
Amazon Linux 2016.09 and opsworks_nodejs

### ISSUE THREAD

**Issue by adammathys** [aws/opsworks-cookbooks#399]
Recently, while upgrade some servers I came across a version issue between Amazon Linux 2016.09 and the Node.js cookbook.

Specifically, [this documentation](http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-os-linux.html#workinginstances-os-amazon) indicates that currently the only version of Node.js that is support by Amazon Linux 2016.09 is 0.12.15. Unfortunately the version the [Chef 11.10 cookbooks](https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.10/opsworks_nodejs/attributes/opsworks_nodejs.rb#L19) default to is 0.12.10.

For what it's worth, it's very easy to get around the issue by manually specifying the version for Node.js but I was more curious if the default shouldn't be updated to work with the most recent Amazon Linux version.

**Comment by githuesch** [comment]
This only looks like an issue. The Node.js version in that attribute file isn't used because the Node.js version is always specified in the JSON blob we send with a command. The documentation is still accurate. We might as well get rid of this attribute altogether and Node.js apps would still work.
