### ISSUE TITLE
Unicorn master process not receiving QUIT

### ISSUE THREAD

**Issue by apanzerj** [aws/opsworks-cookbooks#400]
So when preload_app = true (which it does by default) the method for restart is to send USR2 and then QUIT.

The way that this is accomplished is by using the unicorn conf / before_fork block that sends the QUIT signal to the pid in the old_pid file.

It seems like this isn't really happening because:

1. The original process running (as master) if you lsof -p (pid) you find it is referencing the old path, not the new path of the deploy. Lsof output below:

![image](https://cloud.githubusercontent.com/assets/1709515/21065215/ebb6f8c8-be13-11e6-9abe-526ec500a01e.png)

2. Oddly, the old_pid file does get renamed to unicorn.pid despite the restart not succeeding.

3. In the after_restart.rb you can see, if you ls the pids dir, you see it's got old_pid, which means the QUIT signal hasn't been sent and the fork hasn't actually happened.

Thoughts? Help?

**Comment by apanzerj** [comment]
*bump* any help would be really appreciated.

**Comment by dignoe** [comment]
I'm also having problems with my deploys not picking up the new code. If I deploy some minor changes (no gemfile or migrations), the unicorn workers do not pick up the changes. They are still looking at the old release!

**Comment by apanzerj** [comment]
moved on, closing issue....
