### ISSUE TITLE
[2017-08-11T13:48:48+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out

### ISSUE THREAD

**Issue by AvkashKana** [aws/opsworks-cookbooks#416]
We're seeing this error on opsworks when we try to deploy new servers. We have time-based instances setup that configures correctly but any new server that's added fails to setup.

Does anyone know why this is happening? It's happening across our entire stack.

Thanks in advance for your help!

Best,

Avkash

**Comment by jweiss** [comment]
Closing for now, please reopen if this is still a problem.
