### ISSUE TITLE
NodeJS package gets reinstalled on each deploy

### ISSUE THREAD

**Issue by timhaines** [aws/opsworks-cookbooks#42]
The recipe for installing the node js package installs it even if it's the same version as already installed.  (I think..)

Switching to using the package resource install action and specifying the source would prevent this.

It's here: https://github.com/aws/opsworks-cookbooks/blob/master/opsworks_nodejs/recipes/default.rb

**Comment by awsrequena** [comment]
The package will only be downloaded, if there is no nodejs installed or the version doesn't match the expected one.

``` ruby
   not_if do
      ::File.exists?("/usr/local/bin/node") &&
      system("/usr/local/bin/node -v | grep -q '#{node[:opsworks_nodejs][:version]}'")
    end
```

and nodejs will only be installed, if a package was successfully downloaded

``` ruby
  execute "Install node.js #{node[:opsworks_nodejs][:version]}" do
    cwd "/tmp"
    command "dpkg -i /tmp/#{node[:opsworks_nodejs][:deb]}"

    only_if do
      ::File.exists?("/tmp/#{node[:opsworks_nodejs][:deb]}")
    end
  end
```

The nodejs package will be deleted after the recipe is through. We don't use the package resource here, because currently we host our packages as simple files on S3.

I don't really see the problem you are describing.

**Comment by timhaines** [comment]
@awsrequena Hey, thanks for the response.  I'm using a slightly tweaked recipe, so it's possible I've done something to exclude it, but I don't see the nodejs package file being deleted after the recipe is through.  Can you point me to the location in the recipes that takes care of that please?

BTW - dpkg has a -E option that lets you skip the install if it's the same version.

**Comment by awsrequena** [comment]
Sorry, for the misleading information.  The deletion of the package is not committed into master jet.

Thanks for the tipp, with the '-E'. The thing is that we don't want to download the agent unless it's necessary. Thus saving the download time.

**Comment by timhaines** [comment]
@awsrequena So with what's in master the installation is currently happening on each deploy right?

BTW - the package resource can also have an attribute called :source which can be used to specify a local file.  i.e. /tmp/my-node-package.deb.  The package resource is smart enough not to run the reinstall if the version already matches, although I haven't checked how it does this.

**Comment by awsrequena** [comment]
You got me. Yes indeed, that code is installing the package every time ... that's why the deleting is on it's way.

I'll check if we can use that ":source" attribute.

Thanks again for the tipps.
