### ISSUE TITLE
Ruby 2.6.0

### ISSUE THREAD

**Issue by inopinatus** [aws/opsworks-cookbooks#428]
Ruby 2.6.0 was released on 2018-12-25 with new features and performance improvements. https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/

Please support Ruby 2.6.x.

**Comment by cameronbourgeois** [comment]
@inopinatus It looks like they've added support for Ruby 2.6 on the legacy Chef 11 stacks on May 2nd 2019.
![Screenshot 2019-05-13 15 35 45](https://user-images.githubusercontent.com/1127276/57594569-da531b80-7594-11e9-834d-57694499669c.png)
https://docs.aws.amazon.com/opsworks/latest/userguide/history.html
https://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-ruby.html

**Comment by inopinatus** [comment]
On the one hand, I'm glad to see it! 

On the other, we moved off Chef 11 some time ago, because we couldn't stay on 2.3 for the literal _years_ that OpsWorks left it to rot.
