### ISSUE TITLE
Custom cookbook installation fails on second start with EBS

### ISSUE THREAD

**Issue by ryansch** [aws/opsworks-cookbooks#44]
Steps to repro:
1. Have at least one custom cookbook.
2. Create and start an EBS backed instance.
3. Stop instance after it reaches online state.
4. Add at least one additional custom cookbook.
5. Start the EBS backed instance again.
6. The new custom cookbook is not available.

Expected:
Any new cookbooks or updates to existing cookbooks would be available in /opt/aws/opsworks/current/site-cookbooks.

This appears to be an issue with the `only_if` guard here: https://github.com/aws/opsworks-cookbooks/blob/master/opsworks_custom_cookbooks/recipes/checkout.rb#L51

When using EBS backed instances, it will see that the directory already exists and fail to update the custom cookbooks.

**Comment by bratke** [comment]
i have a similar issue:

custom cookbooks do not update on second start with ebs-backend.

Steps to repro:
1. Have at least one custom cookbook.
2. Create and start an EBS backed instance.
3. Stop instance after it reaches online state.
3.b. change/upgrade version of custom cookbooks
4. run "update custom cookbooks" on stack (this will of course not affect offline instances)
5. Start the EBS backed instance again.
6. the custom cookbooks on this instance will be old

especially when using time-based ebs-backed instances this behaviour can bring you in serious trouble.

**Comment by shlomoswidler** [comment]
Not sure this is a bug. The [documented behavior](http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-installingcustom-enable-update.html) is

```
AWS OpsWorks automatically installs the latest cookbooks on new instances when they are started. For existing instances, however, the situation is different:

* Online instances must be manually updated.
* Offline instance store-backed instances, including load-based and time-based instances, do not require a manual update; AWS OpsWorks automatically installs the latest cookbooks when they are restarted.
* Offline EBS-backed 24/7 instances must be restarted and manually updated; AWS OpsWorks does not run the Setup recipes on these instances when they are restarted.
* Offline EBS-backed load-based and time-based instances cannot be manually restarted, so the simplest approach is to delete the offline instances and add new instances to replace them.
Because they are now new instances, AWS OpsWorks will install the current cookbooks when they are started.
```

If you really need the most up-to-date cookbooks on all instances, you can add the recipe <pre>opsworks_custom_cookbooks::update</pre> to the custom recipes for the Configure event. But, this will cause all running instances in the stack to refresh their cookbooks whenever any instance in the stack is started (either launched for the first time, or started from the stopped state) - including the just-started instance.

**Comment by jweiss** [comment]
Today EBS-based instances that are started again after being suspended before do not refresh their cookbooks.
There are workarounds to this but we are working on changing/fixing this and ensuring that all instances do load your cookbooks on setup/boot.

**Comment by bratke** [comment]
nice, please let us know when it is implemented.

**Comment by ryansch** [comment]
Agreed, in the meantime I've moved back to using instance-store root devices.

**Comment by markunsworth** [comment]
Is there any update on this. 

It's pretty frustrating to have to have to delete and recreate 20 time based instances every time we update our cookbooks.

**Comment by rastut** [comment]
Is there update on the issue?

If there are cookbooks that doesn't update, it will generate inconsistence on the platform.

**Comment by mpchoy** [comment]
- You must manually deploy updated custom cookbooks to online instances.
- You do not have to deploy updated custom cookbooks to offline instance store-backed instances, including load-based and time-based instances.
  AWS OpsWorks automatically deploys the current cookbooks when the instances are restarted.
- You must restart offline EBS-backed 24/7 instances and manually deploy your custom cookbooks.
  AWS OpsWorks does not automatically update the custom cookbooks on these instances when they are restarted.
- You cannot restart offline EBS-backed load-based and time-based instances, so the simplest approach is to delete the offline instances and add new instances to replace them.
  Because they are now new instances, AWS OpsWorks will automatically deploy the current custom cookbooks when the instances are started.

From this page: http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-installingcustom-enable-update.html

**Comment by chrisnicola** [comment]
This really needs to be redesigned.

Ideally there should be a way to specify that cookbooks should be updated on boot. Adding `opsworks_custom_cookbooks::update` to configure doesn't help if the cookbook is used in the setup step.

If there is an issue in a custom cookbook that is causing setup to fail, there is no way to update the cookbooks outside of ssh-ing into the box and running it from there. The OpsWorks management interface will not allow any commands to be run if setup fails other than stopping the instance.

This whole setup is pretty much insane.

**Comment by bjornbos** [comment]
I can't believe this. This is a huge issue in my opinion, and this issue has now been open for almost 2.5 years!!

**Comment by chrisnicola** [comment]
We completely reconsidered our decision to use Opsworks based on this an other glaring flaws and undocumented behaviours. At the end of the day we were creating workarounds for everything. I'd guess based on lack of response to anything we've posted in the forums that Opsworks is effectively dead at this point.

**Comment by ryansch** [comment]
I agree. We're in the process of moving everything away from Opsworks.

**Comment by bjornbos** [comment]
I have to say, I feel the same way. Seems like AWS is busy developing all kinds of new services, while giving their loyal Opsworks customers the finger.

**Comment by markunsworth** [comment]
@jweiss - as the owner, can you give some sort of an update on this please.

**Comment by jweiss** [comment]
I'm very sorry for this particular issue to persist so long. We have addressed this issue for Chef 12 for Linux, which we are releasing shortly. In Chef 12 OpsWorks will always delete the custom cookbook directory on Setup.

We will also address this for Chef 11.10 once Chef 12 is released.

Please feel free to reach out to us for any additional requests or if you want to be part of the Chef 12 beta and get this fix immediately.

**Comment by markunsworth** [comment]
@jweiss Great news. Looking forward to Chef 12 for Linux

**Comment by markunsworth** [comment]
Not sure if Chef 12 fixed this as theres no migration option from Chef 11 for existing stacks. However I notice the last opswork agent update included commit https://github.com/aws/opsworks-cookbooks/commit/f6a16a6ab44d9dbddfaec95e961317382bb2ad35 which looks like it will update the cookbooks at the start of a setup run

**Comment by bgilbert6** [comment]
Does that commit apply to windows machines using Chef 12?

**Comment by githuesch** [comment]
@bgilbert6 It doesn't. Windows machines don't use this set of cookbooks at all.

**Comment by jweiss** [comment]
closing as this is a very old issue
