### ISSUE TITLE
ruby_enterprise is always installed on Chef11

### ISSUE THREAD

**Issue by dbaba** [aws/opsworks-cookbooks#50]
### Summary

Please fix `dependencies` cookbook in order for OpsWorks users to include/exclude `ruby_enterprise` depending on `node[:opsworks][:ruby_version]`. Or alternatively, it's nice as well if `ruby_enterprise::default` recipe checks `node[:opsworks][:ruby_version]` before its installation.
### Description

I've found out an issue where OpsWorks with Chef11 always runs site-cookbooks on Ruby 1.8. As long as I looked into the issue, this is caused because the following entry is included in dependencies/metadata.rb:

```
depends "ruby_enterprise"
```

It is impossible to change Ruby version even though I specify the following in the custom JSON:

```
 "opsworks" : {
    "ruby_version" : "1.9.3"
}
```

This is the output of `ruby -v`:

```
ubuntu@akkorokamui:~$ ruby -v
ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2012.02
```

The reason why I need to remove Ruby 1.8.7 is I want to install gems requiring Ruby 1.9+ such as `fog`.

Here is a log when an error occurred because of version mismatch (`--disable-gems` works only for 1.9 or later whereas the installed ruby `/usr/local/bin/ruby` is 1.8.7). 

```
[2013-08-01T06:39:25+00:00] DEBUG: Mixlib::ShellOut::ShellCommandFailed: ruby_block[Compile Custom OpsWorks Run List]
(opsworks_custom_cookbooks::execute line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[Updating Rubygems to 1.8.24]
(opsworks_rubygems::default line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/bin/env LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 /usr/local/bin/ruby --disable-gems setup.rb --no-rdoc --no-ri ----
STDOUT: 
STDERR: /usr/local/bin/ruby: invalid option --disable-gems  (-h will show valid options)
---- End output of /usr/bin/env LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 /usr/local/bin/ruby --disable-gems setup.rb --no-rdoc --no-ri ----
Ran /usr/bin/env LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 /usr/local/bin/ruby --disable-gems setup.rb --no-rdoc --no-ri returned 2
/opt/aws/opsworks/releases/20130726231932_203/vendor/bundle/ruby/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:248:in `invalid!'
/opt/aws/opsworks/releases/20130726231932_203/vendor/bundle/ruby/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:234:in `error!'
(snip)
```

Hope this will be fixed.

**Comment by jweiss** [comment]
The Ruby version for the Chef run is independent and a different one from the one you can set via node[:opsworks][:ruby_version]. 

Currently we only support Ruby 1.8.7 - there is no way to run custom cookbooks with 1.9.

What should work is switching the Ruby version in /usr/local/bin/ruby to 1.9.3.

**Comment by dbaba** [comment]
Thanks. I understood.

BTW, I posted [a gist](https://gist.github.com/dbaba/6148843) for tweaking Route53 on OpsWorks without Fog. Hope this helps someone who has the same problem as me.

**Comment by jweiss** [comment]
If you just want to use Route53 from within a custom recipe, you can also use the already bundled AWS Ruby SDK: http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Route53.html

**Comment by kenyee** [comment]
@jweiss: why are you guys running chef on an ancient version of Ruby?
It's weird that you're still not on at least 1.9 while the rest of the Ruby world has moved on to 2.1... :-)

And you're using Chef 11.4.4 which has ruby 1.9.3 by default embedded in it...

**Comment by neurogenesis** [comment]
+1, would like to be able to use a modern version of ruby so cookbooks don't break on syntax for things like hash assignment using ":"

**Comment by githuesch** [comment]
@kenyee It sounds to me like you're confusing Chef with Omnibus. We're not using the Omnibus installer, but we're working on support for a more modern version of Ruby to run Chef nonetheless.

**Comment by kenyee** [comment]
githuesch: Not confusing it w/ Ombibus AFAIK...you can ask Chef what version of Ruby is embedded in it (it uses an internal version IIRC) and it clearly says 1.8.7 in Opsworks...

**Comment by jgerry** [comment]
+1 for getting Chef beyond Ruby 1.8. We're running into some ugly problems with community cookbooks related to hash ordering and hash assignment using :

**Comment by neurogenesis** [comment]
@githuesch, can you provide a little more information on how ruby is invoked by the initial launch of chef-solo/chef-client on instances managed by opsworks? will baking in a more recent version of ruby into the image result in opsworks using the customer-provided version when running custom cookbooks?

**Comment by githuesch** [comment]
@neurogenesis We don't invoke Ruby explicity. We invoke the chef-solo binary. The Ruby binary used for this is /usr/bin/ruby. In theory, updating that Ruby to 1.9/2.0 would allow you to use new Ruby syntax in cookbooks. I strongly recommend against this. We're working on a more modern Ruby version for Chef runs. Bear with us.

**Comment by jgerry** [comment]
@githuesch Thanks for the update, much appreciated. Glad to know you guys are working on it.

**Comment by mpchoy** [comment]
Sweet! http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11.html
