### ISSUE TITLE
/etc/hosts values lost when opsworks_stack_state_sync runs

### ISSUE THREAD

**Issue by khouse** [aws/opsworks-cookbooks#51]
We currently have an issue where any appended values to /etc/hosts in our cookbooks are lost when the opsworks_stack_state_sync job run. We have a section for Additional hosts like this:

https://gist.github.com/khouse/6159453

We believe there needs to be a way to append the opsworks values into /etc/hosts without losing all the current content

https://github.com/aws/opsworks-cookbooks/tree/master-chef-11.4/opsworks_stack_state_sync

**Comment by jweiss** [comment]
You can easily add your custom content to /etc/hosts by overriding this template:

https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/opsworks_stack_state_sync/templates/default/hosts.erb

See also http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-template-override.html
