### ISSUE TITLE
Deploy shows success even if bundle install failed

### ISSUE THREAD

**Issue by rgalexey** [aws/opsworks-cookbooks#52]
Bundle install failed on some gems but deploy shows success.
I think it is confusing and should get faled state as well.

Installing rmagick (2.13.2)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

/usr/local/bin/ruby extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for gcc... yes
checking for Magick-config... no
Can't install RMagick 2.13.2. Can't find Magick-config in /usr/local/bin:/usr/local/sbin:/opt/aws/opsworks/releases/20130726231932_203/vendor/bundle/ruby/1.8/bin:/opt/aws/opsworks/current/vendor/bundle/ruby/1.8/bin:/bin:/usr/bin:/sbin:/usr/sbin

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers. Check the mkmf.log file for more
details. You may need configuration options.

Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/usr/local/bin/ruby

Gem files will remain installed in /home/deploy/.bundler/rgx1/ruby/1.9.1/gems/rmagick-2.13.2 for inspection.
Results logged to /home/deploy/.bundler/rgx1/ruby/1.9.1/gems/rmagick-2.13.2/ext/RMagick/gem_make.out
An error occurred while installing rmagick (2.13.2), and Bundler cannot
continue.
Make sure that `gem install rmagick -v '2.13.2'` succeeds before bundling.

**Comment by hundredwatt** [comment]
:+1:

**Comment by awsrequena** [comment]
This is fixed at least in the cookbooks for Chef 11.10
