### ISSUE TITLE
gem_package fails outside of setup lifecycle event.

### ISSUE THREAD

**Issue by cheesefactory** [aws/opsworks-cookbooks#53]
It seems that `node[:dependencies]` does not exist outside of the setup lifecycle event.  The problem with this is that when running gem_package that attribute is now required due to a monkey patch added to GemPackage.

see: https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/opsworks_commons/libraries/gem_package.rb#L10

```
      def gem_binary( gem_cmd = node[:dependencies][:gem_binary] )
        set_or_return(:gem_binary,gem_cmd,:kind_of => [ String ])
      end
```

What this means is that if you want to install a gem it needs to take place within a lifecycle event that includes the opsworks dependencies cookbook.

**Comment by awsrequena** [comment]
Thanks for the hint, a fix will be out soon.

**Comment by estahn** [comment]
:+1:

**Comment by awsrequena** [comment]
This file was removed https://github.com/aws/opsworks-cookbooks/commit/ba55eedfde54c0c7e5c2fd02b0391569cc327320
