### ISSUE TITLE
memcached cluster not supported

### ISSUE THREAD

**Issue by thomasritz** [aws/opsworks-cookbooks#54]
As we have a couple of OpsWorks instances running that host a Rails application, I wanted to utilize the spare memory of each of these instances for memory caching. The instances have enough memory free that it seems unreasonable to launch a separate instance just for memcached. So I assigned all instances the "Memcached" layer in addition to "Rails App Server".

Memcached itself as well as the Ruby client Dalli support clustering. OpsWorks doesn't provide the info: the memcached.yml contain only one IP. I guess it's just the IP of the first Memcached instance. Additional instances are not listed.

As mentioned in https://forums.aws.amazon.com/message.jspa?messageID=428260 the json contains the key node[:opsworks][:layers][:memcached][:instances] which lists all instances.

I'd like to have the generated memcached.yml not only contain one IP address but the IP addresses of all instances of the "Memcached" layer.

**Comment by jweiss** [comment]
You can easily do this by overriding the memcached.yml template, see http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-template-override.html

**Comment by thomasritz** [comment]
FYI. My overridden memcached.yml.erb:

https://gist.github.com/thomasritz/6388112

**Comment by jbraeuer** [comment]
I will close the issue, as it seems solved. Please feel free to re-open if this is not the case.
