### ISSUE TITLE
Update Node.js to v0.10.21 security update

### ISSUE THREAD

**Issue by apriendeau** [aws/opsworks-cookbooks#71]
This is also needed by all node.js apps that run on 0.10 because this also fixes a bug with closing connections too soon.

**Comment by dickhardt** [comment]
Any timeline for updating to 0.10.21?

**Comment by apriendeau** [comment]
We had to fork this repo because there was no response.

**Comment by timhaines** [comment]
@dickhardt @apriendeau  @jweiss told me on Twitter that it's 0.10.21+ that get's deployed already, but they haven't updated the cookbooks on github yet. https://twitter.com/jweiss/status/421193794575691776

It'd be nice if the published cookbooks were what was used.

**Comment by dickhardt** [comment]
I don't know what @jweiss twitter feed means. node --version reports v0.10.11

@apriendeau is there a fork that others are cooperating on?

**Comment by timhaines** [comment]
@dickhardt okay.  FWIW I'm installing node from Chris Lea's packages.  https://launchpad.net/~chris-lea/+archive/node.js/

**Comment by apriendeau** [comment]
@dickhardt not that I am aware of.  @timhaines yes but that is now behind as well because it only does node.js 0.10.15. I modified it a bit. I am ready to create a public for of it.

**Comment by timhaines** [comment]
@apriendeau I'm pretty sure he's made a package for v0.10.25

**Comment by jweiss** [comment]
We have packages for 0.10.24 and 0.10.25 that we are going to publish very soon.

**Comment by dickhardt** [comment]
@jweiss have these packages been published? Am I confused and just don't know where to look? 
0.10.26 just came out today

**Comment by githuesch** [comment]
In the layer settings for a Node.js layer you can select the Node.js version.
Options include 0.10.21, 0.10.24, 0.10.25.

**Comment by jweiss** [comment]
@dickhardt you can select 0.10.21, 0.10.24, or 0.10.25 in the settings of the Node.js layer

**Comment by githuesch** [comment]
@apriendeau @dickhardt Given that this issue was opened for providing 0.10.21, can we close it now?

**Comment by dickhardt** [comment]
yes, thanks!

**Comment by apriendeau** [comment]
Yep thank you!
