### ISSUE TITLE
opsworks_stack_state_sync does not run

### ISSUE THREAD

**Issue by dstieglitz** [aws/opsworks-cookbooks#74]
Hi folks,

We rely on the local hostnames injected into /etc/hosts by the opsworks_stack_state_sync job but we've found that sometimes it doesn't run, especially if you re-run the setup using the opsworks-agent-cli.

Also, examining the output of get_json, we see for example that the monitoring_master is not defined (although the connection to our Ganglia instance seems to be up).

Can the opsworks_stack_state_sync job be run manually or more reliably?

**Comment by jweiss** [comment]
If you re-run an event with the CLI it does so using the JSON info already on the machine.
It does not get updated data from the backend.

So if you added hosts in the meanwhile, /etc/hosts will not change.

Does this explain your problem?

**Comment by Pneumatus** [comment]
I have observed the same issue, especially when starting lots of instances (20+) at the same time - although every instance has run several configure events, some are missing entries in /etc/hosts (and also any other of my recipes that rely on node[:opsworks][:layers] being populated fully.

**Comment by dstieglitz** [comment]
We are not adding anything to the /etc/hosts file. We just need the stack instances to be properly reflected in the hosts file and as Pneumatus says it doesn't always happen. 

We have a small stack but we are forced to stagger startup of our instances to ensure that the hosts are properly populated. What I was asking was if there was a way to force run the job so we can update the hosts file on command before, for example, connecting to a database by host name.

**Comment by Pneumatus** [comment]
While I've not been able to create a reliable reproduction case, this issue doesn't just impact the opsworks_stack_state_sync recipe - the actual underlying issue is definitely that on configure events, sometimes node[:opswork][:layers] isn't fully populated with the state of the whole stack - this is most commonly observed when multiple instances complete their setup stage near the same time, but I've also observed it with a single instance launch triggering configure events which contain incomplete JSON.

**Comment by jweiss** [comment]
We have a new agent that is better at handling many configure events within a short amount of time, even if they are unordered. This should address the issue you are describing.

We can roll it out to your stacks if you give us the OpsWorks Stack ID.

**Comment by awsrequena** [comment]
should be fixed.
