### ISSUE TITLE
opsworks_ganglia fails not_if test for remote_file fetch on Ubuntu

### ISSUE THREAD

**Issue by jsierles** [aws/opsworks-cookbooks#89]
This happens because the following line checks for the package architecture. Ubuntu's default format for package queries doesn't include the architecture.

```
`dpkg-query --show #{package_name} | cut -f 2`.chomp.eql?(node[:ganglia][:package_arch])
```

**Comment by jsierles** [comment]
See pull request #94 for a fix.

**Comment by awsrequena** [comment]
fixed with merged pull request
